# IMDB
--------

## About Dataset

### The purpose of this dataset is to gain insights into the trends of game genre popularity. 
I am particularly interested in the following questions:


Which game genres are the most popular?
What are the trends in popularity for each game genre?
Can we identify any relationship between plot, genre, and popularity?
Can we use generative NLP to generate catchy game titles or plots?
Description
As such, the data was collected from IMDB from the following nine genres of video games: 

* Action
* Adventure
* Comedy
* Crime
* Family
* Fantasy
* Mystery
* Sci-Fi
* Thriller
* The collected data consists of around 20K titles.

### MAIN GOALS OF PROJECTS FOR OUTPUT:

* game_name
* count of versions
* 1st launch
* latest launch
* tenure
* games launched last 10 yrs
* total_votes
* avg_rating
* lowest rating
* highest rating
* rating_count > overall avg
* count_of versions_greater_than_avg_rating
* distinct certifications
* distinct genures
* traffic contribution(game votes/overall votes)
* rank(based on votes)
* rank(based on ratings)
* rank(based on launch consistency)
* rank(based on traffic)
* The below notebook is a dive deep of the IMDB dataset using advanced SQL

### These are the visualized final output

In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_c)

In [9]:


df= pd.read_csv(r'D:/Datasets/SQL/imdb-videogames.csv/imdb-videogames.csv')

df.head()

,Unnamed: 0,name,url,year,certificate,rating,votes,plot,Action,Adventure,Comedy,Crime,Family,Fantasy,Mystery,Sci-Fi,Thriller
0,0,Spider-Man,https://www.imdb.com/title/tt5807780/?ref_=adv...,2018.0,T,9.2,"20,759","When a new villain threatens New York City, Pe...",True,True,False,False,False,True,False,False,False
1,1,Red Dead Redemption II,https://www.imdb.com/title/tt6161168/?ref_=adv...,2018.0,M,9.7,"35,703",Amidst the decline of the Wild West at the tur...,True,True,False,True,False,False,False,False,False
2,2,Grand Theft Auto V,https://www.imdb.com/title/tt2103188/?ref_=adv...,2013.0,M,9.5,"59,986",Three very different criminals team up for a s...,True,False,False,True,False,False,False,False,False
3,3,God of War,https://www.imdb.com/title/tt5838588/?ref_=adv...,2018.0,M,9.6,"26,118","After wiping out the gods of Mount Olympus, Kr...",True,True,False,False,False,False,False,False,False
4,4,Uncharted 4: A Thief's End,https://www.imdb.com/title/tt3334704/?ref_=adv...,2016.0,T,9.5,"28,722",Thrown back into the dangerous underworld he'd...,True,True,False,False,False,False,False,False,False

In [10]:
df.head()

,Unnamed: 0,name,url,year,certificate,rating,votes,plot,Action,Adventure,Comedy,Crime,Family,Fantasy,Mystery,Sci-Fi,Thriller
0,0,Spider-Man,https://www.imdb.com/title/tt5807780/?ref_=adv...,2018.0,T,9.2,"20,759","When a new villain threatens New York City, Pe...",True,True,False,False,False,True,False,False,False
1,1,Red Dead Redemption II,https://www.imdb.com/title/tt6161168/?ref_=adv...,2018.0,M,9.7,"35,703",Amidst the decline of the Wild West at the tur...,True,True,False,True,False,False,False,False,False
2,2,Grand Theft Auto V,https://www.imdb.com/title/tt2103188/?ref_=adv...,2013.0,M,9.5,"59,986",Three very different criminals team up for a s...,True,False,False,True,False,False,False,False,False
3,3,God of War,https://www.imdb.com/title/tt5838588/?ref_=adv...,2018.0,M,9.6,"26,118","After wiping out the gods of Mount Olympus, Kr...",True,True,False,False,False,False,False,False,False
4,4,Uncharted 4: A Thief's End,https://www.imdb.com/title/tt3334704/?ref_=adv...,2016.0,T,9.5,"28,722",Thrown back into the dangerous underworld he'd...,True,True,False,False,False,False,False,False,False

In [11]:
# import sqlalchemy and create a sqlite engine
from sqlalchemy import create_engine
engine = create_engine('sqlite://', echo=False)

# export the dataframe as a table 'playstore' to the sqlite engine
df.to_sql("videogame", con =engine) ## salary dataset is the table name

In [12]:
sql='''

Select * from videogame
limit 5


''';

    
df_sql = pd.read_sql_query(sql,con=engine)
df_sql.head()

,index,Unnamed: 0,name,url,year,certificate,rating,votes,plot,Action,Adventure,Comedy,Crime,Family,Fantasy,Mystery,Sci-Fi,Thriller
0,0,0,Spider-Man,https://www.imdb.com/title/tt5807780/?ref_=adv...,2018.0,T,9.2,"20,759","When a new villain threatens New York City, Pe...",1,1,0,0,0,1,0,0,0
1,1,1,Red Dead Redemption II,https://www.imdb.com/title/tt6161168/?ref_=adv...,2018.0,M,9.7,"35,703",Amidst the decline of the Wild West at the tur...,1,1,0,1,0,0,0,0,0
2,2,2,Grand Theft Auto V,https://www.imdb.com/title/tt2103188/?ref_=adv...,2013.0,M,9.5,"59,986",Three very different criminals team up for a s...,1,0,0,1,0,0,0,0,0
3,3,3,God of War,https://www.imdb.com/title/tt5838588/?ref_=adv...,2018.0,M,9.6,"26,118","After wiping out the gods of Mount Olympus, Kr...",1,1,0,0,0,0,0,0,0
4,4,4,Uncharted 4: A Thief's End,https://www.imdb.com/title/tt3334704/?ref_=adv...,2016.0,T,9.5,"28,722",Thrown back into the dangerous underworld he'd...,1,1,0,0,0,0,0,0,0

## business problem

### *Problem:* we have a requirement to create a new spider name, would this make sense?basically will this sell or not and we are preparing a metrics to check if recurring games are hot selling ###

## 

## Approach:

* we can filter out all the spider man verision

* we can check for the tenure of the game

* we can check the avg rating of all the games (with more than 1 version)

* avg votes/total votes

* we can create a dummy revenume field with random data and see if the trend can make sense

In [15]:
## write a query that talks about tenure of the games



## count of games (we need to change this > <)
sql='''

Select 
'Total overall games' as heading,
count(distinct name) as valuesss
from videogame
where name like '%Spider-Man%'

union

select
'Total games by Spider Man between 1980 and 1985' as heading,
count(distinct name) as valuesss
from videogame
where name like '%Spider-Man%'
and year between 1980 and 1985

union

select
'Total games by Spider Man between 1985 and 1990' as heading,
count(distinct name) as valuesss
from videogame
where name like '%Spider-Man%'
and year between 1985 and 1990

union

select
'Total games by Spider Man between 1990 and 1995' as heading,
count(distinct name) as valuesss
from videogame
where name like '%Spider-Man%'
and year between 1990 and 1995

union

select
'Total games by Spider Man between 1995 and 2000' as heading,
count(distinct name) as valuesss
from videogame
where name like '%Spider-Man%'
and year between 1995 and 2000

union

select
'Total games by Spider Man between 2000 and 2005' as heading,
count(distinct name) as valuesss
from videogame
where name like '%Spider-Man%'
and year between 2000 and 2005
union

select
'Total games by Spider Man between 2005 and 2010' as heading,
count(distinct name) as valuesss
from videogame
where name like '%Spider-Man%'
and year between 2005 and 2010
union

select
'Total games by Spider Man between 2010 and 2015' as heading,
count(distinct name) as valuesss
from videogame
where name like '%Spider-Man%'
and year between 2010 and 2015
union

select
'Total games by Spider Man between 2015 and 2020' as heading,
count(distinct name) as valuesss
from videogame
where name like '%Spider-Man%'
and year between 2015 and 2020
union

select
'Total games by Spider Man between 2020 and 2025' as heading,
count(distinct name) as valuesss
from videogame
where name like '%Spider-Man%'
and year between 2020 and 2025

''';

    
df_sql = pd.read_sql_query(sql,con=engine)
df_sql

                                           heading  valuesss
0  Total games by Spider Man between 1980 and 1985         2
1  Total games by Spider Man between 1985 and 1990         1
2  Total games by Spider Man between 1990 and 1995        11
3  Total games by Spider Man between 1995 and 2000         6
4  Total games by Spider Man between 2000 and 2005         9
5  Total games by Spider Man between 2005 and 2010         7
6  Total games by Spider Man between 2010 and 2015         5
7  Total games by Spider Man between 2015 and 2020         5
8  Total games by Spider Man between 2020 and 2025         2
9                              Total overall games        34

based on the above we would need to study how many games are lauched year to year (we need a query which year vs count of games , write a new to say if it consistent or not , consitent it should deliver or not)

#### would my audience need that?

In [16]:
## tenure
sql='''


Select 
'Spider Man' as game,
min(year) as start_year,
max(year) as end_year,
max(year)-min(year) as tenure
from videogame
where name like '%Spider-Man%'


''';

    
df_sql = pd.read_sql_query(sql,con=engine)
df_sql.head()

         game  start_year  end_year  tenure
0  Spider Man      1982.0    2023.0    41.0

In [17]:
## how many versions where launched before 2000s and after 2000s


sql='''

select
'Total games by Spider Man after 2000' as heading,
count(distinct name) as valuesss
from videogame
where name like '%Spider-Man%'
and year > 2000


''';

    
df_sql = pd.read_sql_query(sql,con=engine)
df_sql.head()

                                heading  valuesss
0  Total games by Spider Man after 2000        22

In [18]:
## playground query 1

## avg metric table
sql='''

select 'total votes' as description, count(*) as value from videogame
union
select 'total votes > 1000' as description, count(*) as value from videogame where votes > 1000
union
select 'total votes < 1000' as description, count(*) as value from videogame where votes < 1000
union
select 'total votes  is null' as description, count(*) as value from videogame where votes is null

union

select 'total avg rating' as description, count(*) as value from videogame
union
select 'total rating greater than avg' as description, count(*) as value from videogame where rating > 7.05
union
select 'total rating lesser than avg' as description, count(*) as value from videogame where votes < 7.05
union
select 'total rating  is null' as description, count(*) as value from videogame where rating is null

''';

    
df_sql = pd.read_sql_query(sql,con=engine)
df_sql.head(10)

                     description  value
0               total avg rating  20803
1          total rating  is null   9203
2  total rating greater than avg   6619
3   total rating lesser than avg   9863
4                    total votes  20803
5           total votes  is null   9203
6             total votes < 1000    841
7             total votes > 1000  10759

In [19]:
## Step 1 Create a main games field.

## to get we will filter the games which are popular (metric for that is each game should be greater than avg rating and avg number of votes)

sql='''

with filter_raw_data as 
(
with filtered_not_null as (
select
*
from
videogame 
where 
rating is not null 
or votes is not null
order by 1 asc
)

select * from filtered_not_null
where rating > (select avg(rating) from filtered_not_null)
and votes > (select avg(votes) from filtered_not_null)

)

select
name,
rating,
votes,
case 
when name like 'Goodbye, Galaxy!%' then 'Goodbye, Galaxy!'
when name like '.hack//%' then '.hack//G.U.'
when name like '13 Sentinels%' then '13 Sentinels'
when name like '3D Pinball for Windows%' then '3D Pinball for Windows'
when name like '80 Days:%' then '80 Days'
when name like 'AI: The Somnium Files%' then 'AI: The Somnium Files'
when name like 'Accounting%' then 'Accounting'
when name like 'Ace Attorney%' then 'Ace Attorney'
when name like 'Ace Combat%' then 'Ace Combat'
when name like 'ActRaiser%' then 'ActRaiser'
when name like 'Advance Wars%' then 'Advance Wars'
when name like 'Adventure%' then 'Adventure'
when name like 'Agatha Christie%' then 'Agatha Christie'
when name like 'Age of Empires%' then 'Age of Empires'
when name like 'Age of Wonders%' then 'Age of Wonders'
when name like 'Adventure%' then 'Adventure'
when name like 'Aladdin%' then 'Aladdin'
when name like 'Alan Wake%' then 'Alan Wake'
when name like 'Alien%' then 'Alien'
when name like 'Aliens%' then 'Aliens'
when name like 'Alone in the Dark%' then 'Alone in the Dark'
when name like 'Alpha%' then 'Alpha'
when name like 'Alter%' then 'Alter'
when name like 'Alto%' then 'Alto'
when name like 'Angry Birds%' then 'Angry Birds'
when name like 'Animal%' then 'Animal'
when name like 'Animaniacs%' then 'Animaniacs'
when name like 'Ape Escape%' then 'Ape Escape'
when name like 'Arc the Lad%' then 'Arc the Lad'
when name like 'Ariel%' then 'Ariel'
when name like 'ArmA%' then 'ArmA'
when name like 'Army Men%' then 'Army Men'
when name like 'Asheron%' then 'Asheron Call'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Assassin%' and name like '%Creed%' then 'Assassin Creed'
when name like 'Atelier Iris%' then 'Atelier Iris'
when name like 'Atlantis%'  then 'Atlantis'
when name like 'Attack on Titan%' then 'Attack on Titan'
when name like 'Avatar%' then 'Avatar'
when name like 'Back to the Future%' then 'Back to the Future'
when name like 'Badland%' then 'Badland'
when name like 'Bakugan%' then 'Bakugan'
when name like 'Baldur%' and name like '%Gate%' then 'Baldur Gate'
when name like 'Barbie%' then 'Barbie'
when name like 'Baten Kaitos%' then 'Baten Kaitos'
when name like 'Battalion Wars%' then 'Battalion Wars'
when name like 'Battlefield%' then 'Battlefield'
else name end as main_name
from filter_raw_data
order by 1 asc

''';

    
df_sql = pd.read_sql_query(sql,con=engine)
df_sql.head()

,name,rating,votes,main_name
0,"'Goodbye, Galaxy!' Episode IV: Secret of the O...",7.7,99,"'Goodbye, Galaxy!' Episode IV: Secret of the O..."
1,"'Goodbye, Galaxy!' Episode V: The Armageddon M...",7.4,82,"'Goodbye, Galaxy!' Episode V: The Armageddon M..."
2,.hack//G.U. Last Recode,7.8,34,.hack//G.U.
3,.hack//G.U. Vol.1//Rebirth,7.8,85,.hack//G.U.
4,.hack//G.U. Vol.2//Reminisce,7.1,42,.hack//G.U.

In [20]:
## Step 1 Create a main games field.

## to get we will filter the games which are popular (metric for that is each game should be greater than avg rating and avg number of votes)

sql='''

with filter_raw_data2 as
(
with filter_raw_data as 
(
with filtered_not_null as (
select
*
from
videogame 
where 
rating is not null 
or votes is not null
order by 1 asc
)

select * from filtered_not_null
where rating > (select avg(rating) from filtered_not_null)
and votes > (select avg(votes) from filtered_not_null)

)

select
name,
rating,
votes,
case 
when name like 'Goodbye, Galaxy!%' then 'Goodbye, Galaxy!'
when name like '.hack//%' then '.hack//G.U.'
when name like '13 Sentinels%' then '13 Sentinels'
when name like '3D Pinball for Windows%' then '3D Pinball for Windows'
when name like '80 Days:%' then '80 Days'
when name like 'AI: The Somnium Files%' then 'AI: The Somnium Files'
when name like 'Accounting%' then 'Accounting'
when name like 'Ace Attorney%' then 'Ace Attorney'
when name like 'Ace Combat%' then 'Ace Combat'
when name like 'ActRaiser%' then 'ActRaiser'
when name like 'Advance Wars%' then 'Advance Wars'
when name like 'Adventure%' then 'Adventure'
when name like 'Agatha Christie%' then 'Agatha Christie'
when name like 'Age of Empires%' then 'Age of Empires'
when name like 'Age of Wonders%' then 'Age of Wonders'
when name like 'Adventure%' then 'Adventure'
when name like 'Aladdin%' then 'Aladdin'
when name like 'Alan Wake%' then 'Alan Wake'
when name like 'Alien%' then 'Alien'
when name like 'Aliens%' then 'Aliens'
when name like 'Alone in the Dark%' then 'Alone in the Dark'
when name like 'Alpha%' then 'Alpha'
when name like 'Alter%' then 'Alter'
when name like 'Alto%' then 'Alto'
when name like 'Angry Birds%' then 'Angry Birds'
when name like 'Animal%' then 'Animal'
when name like 'Animaniacs%' then 'Animaniacs'
when name like 'Ape Escape%' then 'Ape Escape'
when name like 'Arc the Lad%' then 'Arc the Lad'
when name like 'Ariel%' then 'Ariel'
when name like 'ArmA%' then 'ArmA'
when name like 'Army Men%' then 'Army Men'
when name like 'Asheron%' then 'Asheron Call'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Assassin%' and name like '%Creed%' then 'Assassin Creed'
when name like 'Atelier Iris%' then 'Atelier Iris'
when name like 'Atlantis%'  then 'Atlantis'
when name like 'Attack on Titan%' then 'Attack on Titan'
when name like 'Avatar%' then 'Avatar'
when name like 'Back to the Future%' then 'Back to the Future'
when name like 'Badland%' then 'Badland'
when name like 'Bakugan%' then 'Bakugan'
when name like 'Baldur%' and name like '%Gate%' then 'Baldur Gate'
when name like 'Barbie%' then 'Barbie'
when name like 'Baten Kaitos%' then 'Baten Kaitos'
when name like 'Battalion Wars%' then 'Battalion Wars'
when name like 'Battlefield%' then 'Battlefield'
else name end as main_name
from filter_raw_data
order by 1 asc

)

select
main_name,
count(name) as count_of_version
from filter_raw_data2
group by 1
order by 1 asc
''';

    
df_sql = pd.read_sql_query(sql,con=engine)
df_sql.head()

                                           main_name  count_of_version
0  'Goodbye, Galaxy!' Episode IV: Secret of the O...                 1
1  'Goodbye, Galaxy!' Episode V: The Armageddon M...                 1
2                                        .hack//G.U.                 6
3                                        11.22.63 VR                 1
4                                       13 Sentinels                 3

##  we will have master list of all the games from a to z based on which we will proceed with the queries

In [21]:
## Master Query
sql='''

select
*
from
videogame 


''';

    
df_sql = pd.read_sql_query(sql,con=engine)
df_sql.head()

,index,Unnamed: 0,name,url,year,certificate,rating,votes,plot,Action,Adventure,Comedy,Crime,Family,Fantasy,Mystery,Sci-Fi,Thriller
0,0,0,Spider-Man,https://www.imdb.com/title/tt5807780/?ref_=adv...,2018.0,T,9.2,"20,759","When a new villain threatens New York City, Pe...",1,1,0,0,0,1,0,0,0
1,1,1,Red Dead Redemption II,https://www.imdb.com/title/tt6161168/?ref_=adv...,2018.0,M,9.7,"35,703",Amidst the decline of the Wild West at the tur...,1,1,0,1,0,0,0,0,0
2,2,2,Grand Theft Auto V,https://www.imdb.com/title/tt2103188/?ref_=adv...,2013.0,M,9.5,"59,986",Three very different criminals team up for a s...,1,0,0,1,0,0,0,0,0
3,3,3,God of War,https://www.imdb.com/title/tt5838588/?ref_=adv...,2018.0,M,9.6,"26,118","After wiping out the gods of Mount Olympus, Kr...",1,1,0,0,0,0,0,0,0
4,4,4,Uncharted 4: A Thief's End,https://www.imdb.com/title/tt3334704/?ref_=adv...,2016.0,T,9.5,"28,722",Thrown back into the dangerous underworld he'd...,1,1,0,0,0,0,0,0,0

In [22]:
## avg metric table
sql='''

select
'this is the avg rating' as description,
round(avg(rating),2) as metric_avg
from
videogame 

union 

select
'this is the avg votes' as description,
round(avg(votes),2) as metric_avg
from
videogame 

''';

    
df_sql = pd.read_sql_query(sql,con=engine)
df_sql.head()

              description  metric_avg
0  this is the avg rating        7.05
1   this is the avg votes      102.58

In [23]:
## avg metric table
sql='''

select
*,
case 
when name like 'Goodbye, Galaxy!%' then 'Goodbye, Galaxy!'
when name like '.hack//%' then '.hack//G.U.'
when name like '13 Sentinels%' then '13 Sentinels'
when name like '3D Pinball for Windows%' then '3D Pinball for Windows'
when name like '80 Days:%' then '80 Days'
when name like 'AI: The Somnium Files%' then 'AI: The Somnium Files'
when name like 'Accounting%' then 'Accounting'
when name like 'Ace Attorney%' then 'Ace Attorney'
when name like 'Ace Combat%' then 'Ace Combat'
when name like 'ActRaiser%' then 'ActRaiser'
when name like 'Advance Wars%' then 'Advance Wars'
when name like 'Adventure%' then 'Adventure'
when name like 'Agatha Christie%' then 'Agatha Christie'
when name like 'Age of Empires%' then 'Age of Empires'
when name like 'Age of Wonders%' then 'Age of Wonders'
when name like 'Adventure%' then 'Adventure'
when name like 'Aladdin%' then 'Aladdin'
when name like 'Alan Wake%' then 'Alan Wake'
when name like 'Alien%' then 'Alien'
when name like 'Aliens%' then 'Aliens'
when name like 'Alone in the Dark%' then 'Alone in the Dark'
when name like 'Alpha%' then 'Alpha'
when name like 'Alter%' then 'Alter'
when name like 'Alto%' then 'Alto'
when name like 'Angry Birds%' then 'Angry Birds'
when name like 'Animal%' then 'Animal'
when name like 'Animaniacs%' then 'Animaniacs'
when name like 'Ape Escape%' then 'Ape Escape'
when name like 'Arc the Lad%' then 'Arc the Lad'
when name like 'Ariel%' then 'Ariel'
when name like 'ArmA%' then 'ArmA'
when name like 'Army Men%' then 'Army Men'
when name like 'Asheron%' then 'Asheron Call'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Assassin%' and name like '%Creed%' then 'Assassin Creed'
when name like 'Atelier Iris%' then 'Atelier Iris'
when name like 'Atlantis%'  then 'Atlantis'
when name like 'Attack on Titan%' then 'Attack on Titan'
when name like 'Avatar%' then 'Avatar'
when name like 'Back to the Future%' then 'Back to the Future'
when name like 'Badland%' then 'Badland'
when name like 'Bakugan%' then 'Bakugan'
when name like 'Baldur%' and name like '%Gate%' then 'Baldur Gate'
when name like 'Barbie%' then 'Barbie'
when name like 'Baten Kaitos%' then 'Baten Kaitos'
when name like 'Battalion Wars%' then 'Battalion Wars'
when name like 'Battlefield%' then 'Battlefield'
else name end as main_name
from
(
select * from videogame
where
rating is not null 
or votes is not null

) remove_null

where rating > (select avg(rating) from videogame where rating is not null or votes is not null)
and votes >  (select avg(votes) from videogame where rating is not null or votes is not null)

order by 1 asc

''';

    
df_sql = pd.read_sql_query(sql,con=engine)
df_sql.head()

,index,Unnamed: 0,name,url,year,certificate,rating,votes,plot,Action,Adventure,Comedy,Crime,Family,Fantasy,Mystery,Sci-Fi,Thriller,main_name
0,0,0,Spider-Man,https://www.imdb.com/title/tt5807780/?ref_=adv...,2018.0,T,9.2,"20,759","When a new villain threatens New York City, Pe...",1,1,0,0,0,1,0,0,0,Spider-Man
1,1,1,Red Dead Redemption II,https://www.imdb.com/title/tt6161168/?ref_=adv...,2018.0,M,9.7,"35,703",Amidst the decline of the Wild West at the tur...,1,1,0,1,0,0,0,0,0,Red Dead Redemption II
2,2,2,Grand Theft Auto V,https://www.imdb.com/title/tt2103188/?ref_=adv...,2013.0,M,9.5,"59,986",Three very different criminals team up for a s...,1,0,0,1,0,0,0,0,0,Grand Theft Auto V
3,3,3,God of War,https://www.imdb.com/title/tt5838588/?ref_=adv...,2018.0,M,9.6,"26,118","After wiping out the gods of Mount Olympus, Kr...",1,1,0,0,0,0,0,0,0,God of War
4,4,4,Uncharted 4: A Thief's End,https://www.imdb.com/title/tt3334704/?ref_=adv...,2016.0,T,9.5,"28,722",Thrown back into the dangerous underworld he'd...,1,1,0,0,0,0,0,0,0,Uncharted 4: A Thief's End

### The above query
* breakdown 1:- query has a whole had 20k columns
* breakdown 2:- removing all null instances of rating or votes
* breakdown 3:- identifying above avg traffic

In [24]:
## We will use this as our finalized master query

## view  1 :- game names vs count of versions

## assumption :- the game list is not full

sql='''

with master_data as
(
select
*,
case 
when name like 'Goodbye, Galaxy!%' then 'Goodbye, Galaxy!'
when name like '.hack//%' then '.hack//G.U.'
when name like '13 Sentinels%' then '13 Sentinels'
when name like '3D Pinball for Windows%' then '3D Pinball for Windows'
when name like '80 Days:%' then '80 Days'
when name like 'AI: The Somnium Files%' then 'AI: The Somnium Files'
when name like 'Accounting%' then 'Accounting'
when name like 'Ace Attorney%' then 'Ace Attorney'
when name like 'Ace Combat%' then 'Ace Combat'
when name like 'ActRaiser%' then 'ActRaiser'
when name like 'Advance Wars%' then 'Advance Wars'
when name like 'Adventure%' then 'Adventure'
when name like 'Agatha Christie%' then 'Agatha Christie'
when name like 'Age of Empires%' then 'Age of Empires'
when name like 'Age of Wonders%' then 'Age of Wonders'
when name like 'Adventure%' then 'Adventure'
when name like 'Aladdin%' then 'Aladdin'
when name like 'Alan Wake%' then 'Alan Wake'
when name like 'Alien%' then 'Alien'
when name like 'Aliens%' then 'Aliens'
when name like 'Alone in the Dark%' then 'Alone in the Dark'
when name like 'Alpha%' then 'Alpha'
when name like 'Alter%' then 'Alter'
when name like 'Alto%' then 'Alto'
when name like 'Angry Birds%' then 'Angry Birds'
when name like 'Animal%' then 'Animal'
when name like 'Animaniacs%' then 'Animaniacs'
when name like 'Ape Escape%' then 'Ape Escape'
when name like 'Arc the Lad%' then 'Arc the Lad'
when name like 'Ariel%' then 'Ariel'
when name like 'ArmA%' then 'ArmA'
when name like 'Army Men%' then 'Army Men'
when name like 'Asheron%' then 'Asheron Call'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Assassin%' and name like '%Creed%' then 'Assassin Creed'
when name like 'Atelier Iris%' then 'Atelier Iris'
when name like 'Atlantis%'  then 'Atlantis'
when name like 'Attack on Titan%' then 'Attack on Titan'
when name like 'Avatar%' then 'Avatar'
when name like 'Back to the Future%' then 'Back to the Future'
when name like 'Badland%' then 'Badland'
when name like 'Bakugan%' then 'Bakugan'
when name like 'Baldur%' and name like '%Gate%' then 'Baldur Gate'
when name like 'Barbie%' then 'Barbie'
when name like 'Baten Kaitos%' then 'Baten Kaitos'
when name like 'Battalion Wars%' then 'Battalion Wars'
when name like 'Battlefield%' then 'Battlefield'
else name end as main_name
from
(
select * from videogame
where
rating is not null 
or votes is not null

) remove_null

where rating > (select avg(rating) from videogame where rating is not null or votes is not null)
and votes >  (select avg(votes) from videogame where rating is not null or votes is not null)

order by 1 asc

),


count_versions as

(

select
main_name,
count(name) as count_version
from master_data
group by 1
order by 1 desc

),


tenure as (

select
main_name,
launch_year,
latest_year,
case when tenure = 0 then 1 else tenure end as tenure,
case when launch_year >= 2012 and latest_year <= 2022 then 'Yes' else 'No' end as last_ten_yrs_launched
from
(
select
main_name,
min(year) as launch_year,
max(year) as latest_year,
max(year)-min(year) as tenure
from master_data
group by 1
)

)


select
a.main_name,
a.count_version,
b.launch_year,
b.latest_year,
b.tenure,
b.last_ten_yrs_launched
from count_versions a
join tenure b on a.main_name=b.main_name


''';

    
df_sql = pd.read_sql_query(sql,con=engine)
df_sql.head()

,main_name,count_version,launch_year,latest_year,tenure,last_ten_yrs_launched
0,inFamous: Second Son,2,2014.0,2014.0,1.0,Yes
1,inFamous 2,2,2011.0,2011.0,1.0,No
2,inFamous,1,2009.0,2009.0,1.0,No
3,iD3,1,2009.0,2009.0,1.0,No
4,iCarly 2: iJoin the Click,1,2010.0,2010.0,1.0,No

In [25]:
sql='''

with master_data as
(
select
*,
case 
when name like 'Goodbye, Galaxy!%' then 'Goodbye, Galaxy!'
when name like '.hack//%' then '.hack//G.U.'
when name like '13 Sentinels%' then '13 Sentinels'
when name like '3D Pinball for Windows%' then '3D Pinball for Windows'
when name like '80 Days:%' then '80 Days'
when name like 'AI: The Somnium Files%' then 'AI: The Somnium Files'
when name like 'Accounting%' then 'Accounting'
when name like 'Ace Attorney%' then 'Ace Attorney'
when name like 'Ace Combat%' then 'Ace Combat'
when name like 'ActRaiser%' then 'ActRaiser'
when name like 'Advance Wars%' then 'Advance Wars'
when name like 'Adventure%' then 'Adventure'
when name like 'Agatha Christie%' then 'Agatha Christie'
when name like 'Age of Empires%' then 'Age of Empires'
when name like 'Age of Wonders%' then 'Age of Wonders'
when name like 'Adventure%' then 'Adventure'
when name like 'Aladdin%' then 'Aladdin'
when name like 'Alan Wake%' then 'Alan Wake'
when name like 'Alien%' then 'Alien'
when name like 'Aliens%' then 'Aliens'
when name like 'Alone in the Dark%' then 'Alone in the Dark'
when name like 'Alpha%' then 'Alpha'
when name like 'Alter%' then 'Alter'
when name like 'Alto%' then 'Alto'
when name like 'Angry Birds%' then 'Angry Birds'
when name like 'Animal%' then 'Animal'
when name like 'Animaniacs%' then 'Animaniacs'
when name like 'Ape Escape%' then 'Ape Escape'
when name like 'Arc the Lad%' then 'Arc the Lad'
when name like 'Ariel%' then 'Ariel'
when name like 'ArmA%' then 'ArmA'
when name like 'Army Men%' then 'Army Men'
when name like 'Asheron%' then 'Asheron Call'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Assassin%' and name like '%Creed%' then 'Assassin Creed'
when name like 'Atelier Iris%' then 'Atelier Iris'
when name like 'Atlantis%'  then 'Atlantis'
when name like 'Attack on Titan%' then 'Attack on Titan'
when name like 'Avatar%' then 'Avatar'
when name like 'Back to the Future%' then 'Back to the Future'
when name like 'Badland%' then 'Badland'
when name like 'Bakugan%' then 'Bakugan'
when name like 'Baldur%' and name like '%Gate%' then 'Baldur Gate'
when name like 'Barbie%' then 'Barbie'
when name like 'Baten Kaitos%' then 'Baten Kaitos'
when name like 'Battalion Wars%' then 'Battalion Wars'
when name like 'Battlefield%' then 'Battlefield'
else name end as main_name
from
(
select * from videogame
where
rating is not null 
or votes is not null

) remove_null

where rating > (select avg(rating) from videogame where rating is not null or votes is not null)
and votes >  (select avg(votes) from videogame where rating is not null or votes is not null)

order by 1 asc

),

tenure as (

select
main_name,
launch_year,
latest_year,
case when tenure = 0 then 1 else tenure end as tenure
from
(
select
main_name,
min(year) as launch_year,
max(year) as latest_year,
max(year)-min(year) as tenure
from master_data
group by 1
)

)

select * from tenure
''';

    
df_sql = pd.read_sql_query(sql,con=engine)
df_sql.head(10)

,main_name,launch_year,latest_year,tenure
0,"'Goodbye, Galaxy!' Episode IV: Secret of the O...",1991.0,1991.0,1.0
1,"'Goodbye, Galaxy!' Episode V: The Armageddon M...",1991.0,1991.0,1.0
2,.hack//G.U.,2002.0,2017.0,15.0
3,11.22.63 VR,2016.0,2016.0,1.0
4,13 Sentinels,2019.0,2019.0,1.0
5,24: The Game,2006.0,2006.0,1.0
6,3 Skulls of the Toltecs,1996.0,1996.0,1.0
7,3D Ant Attack,1984.0,1984.0,1.0
8,3D Dot Game Heroes,2009.0,2009.0,1.0
9,3D Movie Maker,1995.0,1995.0,1.0

In [22]:
## Master query for Phase 1 in the project!!!

## this is the final query that has all the metrics that we want as a scorecard with the ranking logic applied 
## if 2 metrics are in the ranking system, then another metric will be compared to evaulate and derive the rank
## for example if the votes of name 1 and 2 are same, then avg_rating 1 and 2 will compared, if avg_rating 1 and 2 are same then tenure is compared and etc


sql='''

with master_data as (

select *,
case 
when name like 'Goodbye, Galaxy!%' then 'Goodbye, Galaxy!'
when name like '.hack//%' then '.hack//G.U.'
when name like '13 Sentinels%' then '13 Sentinels'
when name like '3D Pinball for Windows%' then '3D Pinball for Windows'
when name like '80 Days:%' then '80 Days'
when name like 'AI: The Somnium Files%' then 'AI: The Somnium Files'
when name like 'Accounting%' then 'Accounting'
when name like 'Ace Attorney%' then 'Ace Attorney'
when name like 'Ace Combat%' then 'Ace Combat'
when name like 'ActRaiser%' then 'ActRaiser'
when name like 'Advance Wars%' then 'Advance Wars'
when name like 'Adventure%' then 'Adventure'
when name like 'Agatha Christie%' then 'Agatha Christie'
when name like 'Age of Empires%' then 'Age of Empires'
when name like 'Age of Wonders%' then 'Age of Wonders'
when name like 'Adventure%' then 'Adventure'
when name like 'Aladdin%' then 'Aladdin'
when name like 'Alan Wake%' then 'Alan Wake'
when name like 'Alien%' then 'Alien'
when name like 'Aliens%' then 'Aliens'
when name like 'Alone in the Dark%' then 'Alone in the Dark'
when name like 'Alpha%' then 'Alpha'
when name like 'Alter%' then 'Alter'
when name like 'Alto%' then 'Alto'
when name like 'Angry Birds%' then 'Angry Birds'
when name like 'Animal%' then 'Animal'
when name like 'Animaniacs%' then 'Animaniacs'
when name like 'Ape Escape%' then 'Ape Escape'
when name like 'Arc the Lad%' then 'Arc the Lad'
when name like 'Ariel%' then 'Ariel'
when name like 'ArmA%' then 'ArmA'
when name like 'Army Men%' then 'Army Men'
when name like 'Asheron%' then 'Asheron Call'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Assassin%' and name like '%Creed%' then 'Assassin Creed'
when name like 'Atelier Iris%' then 'Atelier Iris'
when name like 'Atlantis%'  then 'Atlantis'
when name like 'Attack on Titan%' then 'Attack on Titan'
when name like 'Avatar%' then 'Avatar'
when name like 'Back to the Future%' then 'Back to the Future'
when name like 'Badland%' then 'Badland'
when name like 'Bakugan%' then 'Bakugan'
when name like 'Baldur%' and name like '%Gate%' then 'Baldur Gate'
when name like 'Barbie%' then 'Barbie'
when name like 'Baten Kaitos%' then 'Baten Kaitos'
when name like 'Battalion Wars%' then 'Battalion Wars'
when name like 'Battlestations%' then 'Battlestations Midway'
when name like '%Battletoads%' then 'Battletoads'
when name like '%Battletoads  Double Dragon%' then 'Battletoads Double Dragon'
when name like '%Battlezone%' then 'Battlezone'
when name like '%Bayonetta & Vanquish 10th Anniversary Bundle%' then 'Bayonetta'
when name like '%Bayonetta 2%' then 'Bayonetta'
when name like '%BeamNG.drive%' then 'BeamNG.drive'
when name like '%Bear in the Big Blue House: Bear Sense of Adventure%' then 'Bear in the Big Blue House: Bear Sense of Adventure'
when name like 'Bear with Me%' then 'Bear with Me'
when name like '%Beat Down: Fists of Vengeance%' then 'Beat Down: Fists of Vengeance'
when name like '%Beautiful Katamari%' then 'Beautiful Katamari'
when name like '%Beavis and Butt-Head%' then 'Beavis and Butt-Head'
when name like 'Beholder%' then 'Beholder'
when name like '%Bendy and the Ink Machine%' then 'Bendy and the Ink Machine'
when name like 'Beyond%' then 'Beyond'
when name like '%BioShock%' then 'BioShock'
when name like '%Black Mirror%' then 'Black Mirror'
when name like 'BlazBlue%' then 'BlazBlue'
when name like 'Blazing Angels%' then 'Blazing Angels'
when name like 'Bloody Roar%' then 'Bloody Roar'
when name like 'Boktai%' then 'Boktai'
when name like 'Bomberman%' then 'Bomberman'
when name like 'Bone%' then 'Bone'
when name like 'Borderlands%' then 'Borderlands'
when name like 'Bloodstained%' then 'Bloodstained'
when name like 'Broken Sword%' then 'Broken Sword'
when name like 'Brothers in Arms%' then 'Brothers in Arms'
when name like 'Buffy the Vampire Slayer%' then 'Buffy the Vampire Slayer'
when name like 'Bugs Bunny%' then 'Bugs Bunny'
when name like 'Bushido Blade%' then 'Bushido Blade'
when name like 'Burnout%' then 'Burnout'
when name like 'CR%' then 'CR'
when name like 'CSI%' then 'CSI'
when name like 'Cadillacs and Dinosaurs%' then 'Cadillacs and Dinosaurs'
when name like 'Call of Duty%' then 'Call of Duty'
when name like 'Call of Juarez%' then 'Call of Juarez'
when name like 'Capcom vs SNK%' then 'Capcom vs SNK'
when name like 'Cat Quest%' then 'Cat Quest'
when name like 'Chaos Rings%' then 'Chaos Rings'
when name like 'Chicken Invaders%' then 'Chicken Invaders'
when name like 'Chip Dale%' then 'Chip Dale'
when name like 'Chivalry%' then 'Chivalry'
when name like 'Close Combat%' then 'Close Combat'
when name like 'Colony Wars%' then 'Colony Wars'
when name like 'Command & Conquer%' then 'Command & Conquer'
when name like 'Castlevania%' then 'Castlevania'
when name like 'Commandos%' then 'Commandos'
when name like 'Castlevania%' then 'Castlevania'
when name like 'Crash Bandicoot%' then 'Crash Bandicoot'
when name like 'Castlevania%' then 'Castlevania'
when name like 'Cube Escape%' then 'Cube Escape'
when name like 'Crysis%' then 'Crysis'
when name like 'Danganronpa%' then 'Danganronpa'
when name like 'Dark Souls%' then 'Dark Souls'
when name like 'Darksiders%' then 'Darksiders'
when name like 'Dead Island%' then 'Dead Island'
when name like 'Dead Space%' then 'Dead Space'
when name like 'Dead or Alive%' then 'Dead or Alive'
when name like 'Deadpool%' then 'Deadpool'
when name like 'Demolition Man%' then 'Demolition Man'
when name like 'Demon Slayer%' then 'Demon Slayer'
when name like 'Descent%' then 'Descent'
when name like 'Deus Ex%' then 'Deus Ex'
when name like 'Devil May Cry%' then 'Devil May Cry'
when name like 'Diablo%' then 'Diablo'
when name like 'Die Hard%' then 'Die Hard'
when name like 'Disciples%' then 'Disciples'
when name like 'Die Hard%' then 'Die Hard'
when name like 'Disgaea%' then 'Disgaea'
when name like 'Dishonored%' then 'Dishonored'
when name like 'Dissidia%' then 'Dissidia'
when name like 'Disney%' then 'Disney'
when name like 'Divinity%' then 'Divinity'
when name like 'Doctor Who%' then 'Doctor Who'
when name like 'Dont Escape%' then 'Dont Escape'
when name like 'Disney%' then 'Disney'
when name like 'Donkey Kong%' then 'Donkey Kong'
when name like 'Doom%' then 'Doom'
when name like 'Double Dragon%' then 'Double Dragon'
when name like 'Dracula%' then 'Dracula'
when name like 'Dragon Age%' then 'Dragon Age'
when name like 'Dragon Ball%' then 'Dragon Ball'
when name like 'Dragon Warrior%' then 'Dragon Warrior'
when name like 'Drakengard%' then 'Drakengard'
when name like 'Duke Nukem%' then 'Duke Nukem'
when name like 'Dungeon%' then 'Dungeon'
when name like 'Dragon Quest%' then 'Dragon Quest'
when name like 'Dynasty Warriors%' then 'Dynasty Warriors'
when name like 'Dragon Quest%' then 'Dragon Quest'
when name like 'Earthworm%' then 'Earthworm'
when name like 'Evil Dead%' then 'Evil Dead'
when name like 'F.E.A.R.%' then 'F.E.A.R.'
when name like 'Fable%' then 'Fable'
when name like 'Dragon Quest%' then 'Dragon Quest'
when name like 'Fallout%' then 'Fallout'
when name like 'Far Cry%' then 'Far Cry'
when name like 'Fatal Frame%' then 'Fatal Frame'
when name like 'Final Fantasy%' then 'Final Fantasy'
when name like 'Fire Emblem%' then 'Fire Emblem'
when name like 'Forza Horizon%' then 'Forza Horizon'
when name like 'Forza Motorsport%' then 'Forza Motorsport'
when name like 'Freddi Fish%' then 'Freddi Fish'
when name like 'Front Mission%' then 'Front Mission'
when name like 'Fullmetal Alchemist%' then 'Fullmetal Alchemist'
when name like 'G.I. Joe%' then 'G.I. Joe'
when name like 'Ghost Recon%' then 'Ghost Recon'
when name like 'Ghost in the Shell%' then 'Ghost in the Shell'
when name like 'God of War%' then 'God of War'
when name like 'Goosebumps%' then 'Goosebumps'
when name like 'Gothic%' then 'Gothic'
when name like 'God of War%' then 'God of War'
when name like 'Grand Theft Auto%' then 'Grand Theft Auto'
when name like 'Gravity Rush%' then 'Gravity Rush'
when name like 'Growlanser%' then 'Growlanser'
when name like 'Guild Wars%' then 'Guild Wars'
when name like 'Guilty Gear%' then 'Guilty Gear'
when name like 'Halo%' then 'Halo'
when name like 'Hatsune Miku%' then 'Hatsune Miku'
when name like 'Heroes of Might and Magic%' then 'Heroes of Might and Magic'
when name like 'Hyperdimension Neptunia%' then 'Hitman'
when name like 'Indiana Jones%' then 'Indiana Jones'
when name like 'Infinity Blade%' then 'Infinity Blade'
when name like 'James Bond 007%' then 'James Bond 007'
when name like 'JoJos Bizarre Adventure%' then 'JoJos Bizarre Adventure'
when name like 'Jurassic%' then 'Jurassic World'
when name like 'Kings Quest%' then 'Kings Quest'
when name like 'Kingdom Hearts%' then 'Kingdom Hearts'
when name like 'Hitman%' then 'Hitman'
when name like 'Kirby%' then 'Kirby'
when name like 'Lands of Lore%' then 'Lands of Lore'
when name like 'Hitman%' then 'Hitman'
when name like 'Lego%' then 'Lego'
when name like 'Leisure Suit%' then 'Leisure Suit'
when name like 'Luigis Mansion%' then 'Luigis Mansion'
when name like 'Mafia%' then 'Mafia'
when name like 'Mario & Luigi%' then 'Mario & Luigi'
when name like 'Mario Party%' then 'Mario Party'
when name like 'Marvel%' then 'Marvel'
when name like 'Mass Effect%' then 'Mass Effect'
when name like 'Mech Commander%' then 'Mech Commander'
when name like 'MechWarrior%' then 'MechWarrior'
when name like 'Medal of Honor%' then 'Medal of Honor'
when name like 'Mega Man%' then 'Mega Man'
when name like 'Metal Gear%' then 'Metal Gear'
when name like 'Metal Slug%' then 'Metal Slug'
when name like 'Middle-Earth%' then 'Middle-Earth'
when name like 'Might and Magic%' then 'Might and Magic'
when name like 'Mobile Suit Gundam%' then 'Mobile Suit Gundam'
when name like 'Modern Combat%' then 'Modern Combat'
when name like 'Monster Hunter%' then 'Monster Hunter'
when name like 'Monster Rancher%' then 'Monster Rancher'
when name like 'Mortal Kombat%' then 'Mortal Kombat'
when name like 'MotorStorm%' then 'MotorStorm'
when name like 'Mount & Blade%' then 'Mount & Blade'
when name like 'Might and Magic%' then 'Might and Magic'
when name like 'My Friend Pedro%' then 'My Friend Pedro'
when name like 'Myst%' then 'Myst'
when name like 'Mystery Case Files%' then 'Mystery Case Files'
when name like 'Nancy Drew%' then 'Nancy Drew'
when name like 'Naruto%' then 'Naruto'
when name like 'Need for Speed%' then 'Need for Speed'
when name like 'Might and Magic%' then 'Might and Magic'
when name like 'Oddworld%' then 'Oddworld'
when name like 'One Piece%' then 'One Piece'
when name like 'Onimusha%' then 'Onimusha'
when name like 'Pac-Man%' then 'Pac-Man'
when name like 'Persona%' then 'Persona'
when name like 'PokÃ©mon%' then 'Pokemon'
when name like 'Power Rangers%' then 'Power Rangers'
when name like 'Prince of Persia%' then 'Prince of Persia'
when name like 'Professor Layton%' then 'Professor Layton'
when name like 'Putt-Putt%' then 'Putt-Putt'
when name like 'Quest for Glory%' then 'Quest for Glory'
when name like 'Putt-Putt%' then 'Putt-Putt'
when name like 'Rainbow Six%' then 'Rainbow Six'
when name like 'Putt-Putt%' then 'Putt-Putt'
when name like 'Ratchet & Clank%' then 'Ratchet & Clank'
when name like 'Red Dead Redemption%' then 'Red Dead Redemption'
when name like 'Resident Evil%' then 'Resident Evil'
when name like 'Road Rash%' then 'Road Rash'
when name like 'RollerCoaster%' then 'RollerCoaster'
when name like 'Rusty Lake%' then 'Rusty Lake'
when name like 'Saints Row%' then 'Saints Row'
when name like 'Sam & Max%' then 'Sam & Max'
when name like 'Samurai Shodown%' then 'Samurai Shodown'
when name like 'Samurai Warriors%' then 'Samurai Warriors'
when name like 'Scooby-Doo%' then 'Scooby-Doo'
when name like 'Serious Sam%' then 'Serious Sam'
when name like 'Samurai Warriors%' then 'Samurai Warriors'
when name like 'Shadow Hearts%' then 'Shadow Hearts'
when name like 'Sherlock Holmes%' then 'Sherlock Holmes'
when name like 'Sleeping Dogs%' then 'Sleeping Dogs'
when name like 'South Park%' then 'South Park'
when name like 'Splatoon%' then 'Splatoon'
when name like 'SpongeBob SquarePants%' then 'SpongeBob SquarePants'
when name like 'Star Ocean%' then 'Star Ocean'
when name like 'Star Trek%' then 'Star Trek'
when name like 'Star Wars%' then 'Star Wars'
when name like 'Street Fighter%' then 'Street Fighter'
when name like 'Super Mario%' then 'Super Mario'
when name like 'Tales of Monkey Island%' then 'Tales of Monkey Island'
when name like 'Teenage Mutant Ninja Turtles%' then 'Teenage Mutant Ninja Turtles'
when name like 'The King of Fighters%' then 'The King of Fighters'
when name like 'The Legend of Heroes%' then 'The Legend of Heroes'
when name like 'The Legend of Zelda%' then 'The Legend of Zelda'
when name like 'The Room%' then 'The Room'
when name like 'The Simpsons%' then 'The Simpsons'
when name like 'The Walking Dead%' then 'The Walking Dead'
when name like 'Ultima%' then 'Ultima'
when name like 'Twisted Metal%' then 'Twisted Metal'
when name like 'Uncharted%' then 'Uncharted'
when name like 'Vader Immortal%' then 'Vader Immortal'
when name like 'Virtua Fighter%' then 'Virtua Fighter'
when name like 'Twisted Metal%' then 'Twisted Metal'
when name like 'WWE%' or name like 'WWF%' then 'WWE'
when name like 'Warhammer%' then 'Warhammer'
when name like 'Wing Commander%' then 'Wing Commander'
when name like 'Wolfenstein%' then 'Wolfenstein'
when name like 'World of Warcraft%' then 'World of Warcraft'
when name like 'X-Men%' then 'X-Men'
when name like 'Xenoblade Chronicles%' then 'Xenoblade Chronicles'
when name like 'Yakuza%' then 'Yakuza'
when name like 'Yu-Gi-Oh%' then 'Yu-Gi-Oh'
when name like 'Zombie Society%' then 'Zombie Society'
when name like 'Zone of the Enders%' then 'Zone of the Enders'
when name like 'inFamous%' then 'inFamous'


else name end as main_name
from 
(
select * from videogame
where
rating is not null 
or votes is not null
)

where rating > (select avg(rating) from videogame where rating is not null or votes is not null)
and votes >  (select avg(votes) from videogame where rating is not null or votes is not null)
)

select
version.main_name,
version.count_version,
tenure_table.launch_year,
tenure_table.latest_year,
tenure_table.tenure,
tenure_table.last_ten_yrs_launched,
total_votes_table.total_votes,
rating.avg_rating,
rating.min_rating,
rating.max_rating,
rating_avg.rating_counts_greater_than_overall_avg,
count_of_versions_greater_than_avg_rating.total_games_greater_than_avg_rating,
cerifications.distinct_certifications,
generes.distinct_generes,
traffic.traffic_contribution,
row_number () over (order by total_votes_table.total_votes desc,rating.avg_rating desc,rating.min_rating desc,rating.max_rating desc,cerifications.distinct_certifications desc,generes.distinct_generes desc,version.count_version desc,rating_avg.rating_counts_greater_than_overall_avg desc) as row_number,
dense_rank () over (order by total_votes_table.total_votes desc,rating.avg_rating desc,rating.min_rating desc,rating.max_rating desc,cerifications.distinct_certifications desc,generes.distinct_generes desc, version.count_version desc,rating_avg.rating_counts_greater_than_overall_avg desc) as rank_number
from (
select
main_name,
count(name) as count_version
from master_data
group by 1) version

join (
select
main_name,
launch_year,
latest_year,
case when tenure = 0 then 1 else tenure end as tenure,
case when launch_year >= 2012 and latest_year <= 2022 then 'Yes' else 'No' end as last_ten_yrs_launched
from
(
select
main_name,
min(year) as launch_year,
max(year) as latest_year,
max(year)-min(year) as tenure
from master_data
group by 1
)

) tenure_table on version.main_name=tenure_table.main_name

join (

select
main_name,
sum(votes) as total_votes
from master_data
group by 1

) total_votes_table on version.main_name=total_votes_table.main_name


join (

select
main_name,
round(avg(rating),2) as avg_rating,
min(rating) as min_rating,
max(rating) as max_rating
from master_data
group by 1

) rating on version.main_name=rating.main_name

join (

select
main_name,
count(rating) as rating_counts_greater_than_overall_avg
from (
select
main_name,
rating,
round((select avg(rating) from master_data),2) as avg_rating
from master_data
where rating > avg_rating
group by 1,2
)
group by 1


) rating_avg on version.main_name=rating_avg.main_name

join (

select
main_name,
sum(greater_than_avg_rating) as total_games_greater_than_avg_rating
from

(
select
main_name,
name,
rating,
round((select avg(rating) from master_data),2) as avg_rating,
case when rating > round((select avg(rating) from master_data),2) then 1 else 0 end as greater_than_avg_rating
from master_data 
group by 1,2
)
group by 1

) count_of_versions_greater_than_avg_rating on version.main_name=count_of_versions_greater_than_avg_rating.main_name

join (

select
main_name,
count(distinct certificate) as distinct_certifications
from
(
select
distinct
main_name,
name,
certificate
from master_data
group by 1,2
)
group by 1

) cerifications on version.main_name=cerifications.main_name

join (

select
main_name,
(Action + adventure + Comedy + Crime + Family + Fantasy + Mystery + SciFi + Thriller) as distinct_generes

from (
select
main_name,
max(action) as action,
max(adventure) as adventure,
max(comedy) as comedy,
max(crime) as crime,
max(Family) as family,
max(Fantasy) as fantasy,
max(Mystery) as mystery,
max([Sci-Fi]) as scifi,
max(Thriller) as thriller
from
(
select
main_name,
name,
Action,
Adventure,
Comedy,
Crime,
Family,
Fantasy,
Mystery,
[Sci-Fi],
Thriller
from master_data
group by 2
)
group by 1
)


)  generes on version.main_name=generes.main_name

join (

select
main_name,
sum(votes)/(select sum(votes) from master_data) as traffic_contribution
from master_data
group by 1


) traffic on version.main_name=traffic.main_name

order by rank_number asc

''';

    
df_sql = pd.read_sql_query(sql,con=engine)
df_sql.head()

,main_name,count_version,launch_year,latest_year,tenure,last_ten_yrs_launched,total_votes,avg_rating,min_rating,max_rating,rating_counts_greater_than_overall_avg,total_games_greater_than_avg_rating,distinct_certifications,distinct_generes,traffic_contribution,row_number,rank_number
0,Star Wars,55,1982.0,2022.0,40.0,No,11253.0,7.88,7.1,9.5,11,21,5,4,0.013623,1,1
1,Kirby,21,1992.0,2022.0,30.0,No,8597.0,7.91,7.1,9.0,7,11,3,6,0.010408,2,2
2,WWE,20,1993.0,2022.0,29.0,No,8268.0,7.64,7.1,8.5,4,5,3,2,0.010010,3,3
3,Lego,26,1997.0,2018.0,21.0,No,7009.0,7.80,7.1,8.7,6,9,2,6,0.008485,4,4
4,Dragon Ball,27,1992.0,2020.0,28.0,No,6893.0,7.70,7.1,8.7,6,9,3,7,0.008345,5,5

In [26]:
## playground query

sql='''

with master_data as
(
select
*,
case 
when name like 'Goodbye, Galaxy!%' then 'Goodbye, Galaxy!'
when name like '.hack//%' then '.hack//G.U.'
when name like '13 Sentinels%' then '13 Sentinels'
when name like '3D Pinball for Windows%' then '3D Pinball for Windows'
when name like '80 Days:%' then '80 Days'
when name like 'AI: The Somnium Files%' then 'AI: The Somnium Files'
when name like 'Accounting%' then 'Accounting'
when name like 'Ace Attorney%' then 'Ace Attorney'
when name like 'Ace Combat%' then 'Ace Combat'
when name like 'ActRaiser%' then 'ActRaiser'
when name like 'Advance Wars%' then 'Advance Wars'
when name like 'Adventure%' then 'Adventure'
when name like 'Agatha Christie%' then 'Agatha Christie'
when name like 'Age of Empires%' then 'Age of Empires'
when name like 'Age of Wonders%' then 'Age of Wonders'
when name like 'Adventure%' then 'Adventure'
when name like 'Aladdin%' then 'Aladdin'
when name like 'Alan Wake%' then 'Alan Wake'
when name like 'Alien%' then 'Alien'
when name like 'Aliens%' then 'Aliens'
when name like 'Alone in the Dark%' then 'Alone in the Dark'
when name like 'Alpha%' then 'Alpha'
when name like 'Alter%' then 'Alter'
when name like 'Alto%' then 'Alto'
when name like 'Angry Birds%' then 'Angry Birds'
when name like 'Animal%' then 'Animal'
when name like 'Animaniacs%' then 'Animaniacs'
when name like 'Ape Escape%' then 'Ape Escape'
when name like 'Arc the Lad%' then 'Arc the Lad'
when name like 'Ariel%' then 'Ariel'
when name like 'ArmA%' then 'ArmA'
when name like 'Army Men%' then 'Army Men'
when name like 'Asheron%' then 'Asheron Call'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Assassin%' and name like '%Creed%' then 'Assassin Creed'
when name like 'Atelier Iris%' then 'Atelier Iris'
when name like 'Atlantis%'  then 'Atlantis'
when name like 'Attack on Titan%' then 'Attack on Titan'
when name like 'Avatar%' then 'Avatar'
when name like 'Back to the Future%' then 'Back to the Future'
when name like 'Badland%' then 'Badland'
when name like 'Bakugan%' then 'Bakugan'
when name like 'Baldur%' and name like '%Gate%' then 'Baldur Gate'
when name like 'Barbie%' then 'Barbie'
when name like 'Baten Kaitos%' then 'Baten Kaitos'
when name like 'Battalion Wars%' then 'Battalion Wars'
when name like 'Battlestations%' then 'Battlestations Midway'
when name like '%Battletoads%' then 'Battletoads'
when name like '%Battletoads  Double Dragon%' then 'Battletoads Double Dragon'
when name like '%Battlezone%' then 'Battlezone'
when name like '%Bayonetta & Vanquish 10th Anniversary Bundle%' then 'Bayonetta'
when name like '%Bayonetta 2%' then 'Bayonetta'
when name like '%BeamNG.drive%' then 'BeamNG.drive'
when name like '%Bear in the Big Blue House: Bear Sense of Adventure%' then 'Bear in the Big Blue House: Bear Sense of Adventure'
when name like 'Bear with Me%' then 'Bear with Me'
when name like '%Beat Down: Fists of Vengeance%' then 'Beat Down: Fists of Vengeance'
when name like '%Beautiful Katamari%' then 'Beautiful Katamari'
when name like '%Beavis and Butt-Head%' then 'Beavis and Butt-Head'
when name like 'Beholder%' then 'Beholder'
when name like '%Bendy and the Ink Machine%' then 'Bendy and the Ink Machine'
when name like 'Beyond%' then 'Beyond'
when name like '%BioShock%' then 'BioShock'
when name like '%Black Mirror%' then 'Black Mirror'
when name like 'BlazBlue%' then 'BlazBlue'
when name like 'Blazing Angels%' then 'Blazing Angels'
when name like 'Bloody Roar%' then 'Bloody Roar'
when name like 'Boktai%' then 'Boktai'
when name like 'Bomberman%' then 'Bomberman'
when name like 'Bone%' then 'Bone'
when name like 'Borderlands%' then 'Borderlands'
when name like 'Bloodstained%' then 'Bloodstained'
when name like 'Broken Sword%' then 'Broken Sword'
when name like 'Brothers in Arms%' then 'Brothers in Arms'
when name like 'Buffy the Vampire Slayer%' then 'Buffy the Vampire Slayer'
when name like 'Bugs Bunny%' then 'Bugs Bunny'
when name like 'Bushido Blade%' then 'Bushido Blade'
when name like 'Burnout%' then 'Burnout'
when name like 'CR%' then 'CR'
when name like 'CSI%' then 'CSI'
when name like 'Cadillacs and Dinosaurs%' then 'Cadillacs and Dinosaurs'
when name like 'Call of Duty%' then 'Call of Duty'
when name like 'Call of Juarez%' then 'Call of Juarez'
when name like 'Capcom vs SNK%' then 'Capcom vs SNK'
when name like 'Cat Quest%' then 'Cat Quest'
when name like 'Chaos Rings%' then 'Chaos Rings'
when name like 'Chicken Invaders%' then 'Chicken Invaders'
when name like 'Chip Dale%' then 'Chip Dale'
when name like 'Chivalry%' then 'Chivalry'
when name like 'Close Combat%' then 'Close Combat'
when name like 'Colony Wars%' then 'Colony Wars'
when name like 'Command & Conquer%' then 'Command & Conquer'
when name like 'Castlevania%' then 'Castlevania'
when name like 'Commandos%' then 'Commandos'
when name like 'Castlevania%' then 'Castlevania'
when name like 'Crash Bandicoot%' then 'Crash Bandicoot'
when name like 'Castlevania%' then 'Castlevania'
when name like 'Cube Escape%' then 'Cube Escape'
when name like 'Crysis%' then 'Crysis'
when name like 'Danganronpa%' then 'Danganronpa'
when name like 'Dark Souls%' then 'Dark Souls'
when name like 'Darksiders%' then 'Darksiders'
when name like 'Dead Island%' then 'Dead Island'
when name like 'Dead Space%' then 'Dead Space'
when name like 'Dead or Alive%' then 'Dead or Alive'
when name like 'Deadpool%' then 'Deadpool'
when name like 'Demolition Man%' then 'Demolition Man'
when name like 'Demon Slayer%' then 'Demon Slayer'
when name like 'Descent%' then 'Descent'
when name like 'Deus Ex%' then 'Deus Ex'
when name like 'Devil May Cry%' then 'Devil May Cry'
when name like 'Diablo%' then 'Diablo'
when name like 'Die Hard%' then 'Die Hard'
when name like 'Disciples%' then 'Disciples'
when name like 'Die Hard%' then 'Die Hard'
when name like 'Disgaea%' then 'Disgaea'
when name like 'Dishonored%' then 'Dishonored'
when name like 'Dissidia%' then 'Dissidia'
when name like 'Disney%' then 'Disney'
when name like 'Divinity%' then 'Divinity'
when name like 'Doctor Who%' then 'Doctor Who'
when name like 'Dont Escape%' then 'Dont Escape'
when name like 'Disney%' then 'Disney'
when name like 'Donkey Kong%' then 'Donkey Kong'
when name like 'Doom%' then 'Doom'
when name like 'Double Dragon%' then 'Double Dragon'
when name like 'Dracula%' then 'Dracula'
when name like 'Dragon Age%' then 'Dragon Age'
when name like 'Dragon Ball%' then 'Dragon Ball'
when name like 'Dragon Warrior%' then 'Dragon Warrior'
when name like 'Drakengard%' then 'Drakengard'
when name like 'Duke Nukem%' then 'Duke Nukem'
when name like 'Dungeon%' then 'Dungeon'
when name like 'Dragon Quest%' then 'Dragon Quest'
when name like 'Dynasty Warriors%' then 'Dynasty Warriors'
when name like 'Dragon Quest%' then 'Dragon Quest'
when name like 'Earthworm%' then 'Earthworm'
when name like 'Evil Dead%' then 'Evil Dead'
when name like 'F.E.A.R.%' then 'F.E.A.R.'
when name like 'Fable%' then 'Fable'
when name like 'Dragon Quest%' then 'Dragon Quest'
when name like 'Fallout%' then 'Fallout'
when name like 'Far Cry%' then 'Far Cry'
when name like 'Fatal Frame%' then 'Fatal Frame'
when name like 'Final Fantasy%' then 'Final Fantasy'
when name like 'Fire Emblem%' then 'Fire Emblem'
when name like 'Forza Horizon%' then 'Forza Horizon'
when name like 'Forza Motorsport%' then 'Forza Motorsport'
when name like 'Freddi Fish%' then 'Freddi Fish'
when name like 'Front Mission%' then 'Front Mission'
when name like 'Fullmetal Alchemist%' then 'Fullmetal Alchemist'
when name like 'G.I. Joe%' then 'G.I. Joe'
when name like 'Ghost Recon%' then 'Ghost Recon'
when name like 'Ghost in the Shell%' then 'Ghost in the Shell'
when name like 'God of War%' then 'God of War'
when name like 'Goosebumps%' then 'Goosebumps'
when name like 'Gothic%' then 'Gothic'
when name like 'God of War%' then 'God of War'
when name like 'Grand Theft Auto%' then 'Grand Theft Auto'
when name like 'Gravity Rush%' then 'Gravity Rush'
when name like 'Growlanser%' then 'Growlanser'
when name like 'Guild Wars%' then 'Guild Wars'
when name like 'Guilty Gear%' then 'Guilty Gear'
when name like 'Halo%' then 'Halo'
when name like 'Hatsune Miku%' then 'Hatsune Miku'
when name like 'Heroes of Might and Magic%' then 'Heroes of Might and Magic'
when name like 'Hyperdimension Neptunia%' then 'Hitman'
when name like 'Indiana Jones%' then 'Indiana Jones'
when name like 'Infinity Blade%' then 'Infinity Blade'
when name like 'James Bond 007%' then 'James Bond 007'
when name like 'JoJos Bizarre Adventure%' then 'JoJos Bizarre Adventure'
when name like 'Jurassic%' then 'Jurassic World'
when name like 'Kings Quest%' then 'Kings Quest'
when name like 'Kingdom Hearts%' then 'Kingdom Hearts'
when name like 'Hitman%' then 'Hitman'
when name like 'Kirby%' then 'Kirby'
when name like 'Lands of Lore%' then 'Lands of Lore'
when name like 'Hitman%' then 'Hitman'
when name like 'Lego%' then 'Lego'
when name like 'Leisure Suit%' then 'Leisure Suit'
when name like 'Luigis Mansion%' then 'Luigis Mansion'
when name like 'Mafia%' then 'Mafia'
when name like 'Mario & Luigi%' then 'Mario & Luigi'
when name like 'Mario Party%' then 'Mario Party'
when name like 'Marvel%' then 'Marvel'
when name like 'Mass Effect%' then 'Mass Effect'
when name like 'Mech Commander%' then 'Mech Commander'
when name like 'MechWarrior%' then 'MechWarrior'
when name like 'Medal of Honor%' then 'Medal of Honor'
when name like 'Mega Man%' then 'Mega Man'
when name like 'Metal Gear%' then 'Metal Gear'
when name like 'Metal Slug%' then 'Metal Slug'
when name like 'Middle-Earth%' then 'Middle-Earth'
when name like 'Might and Magic%' then 'Might and Magic'
when name like 'Mobile Suit Gundam%' then 'Mobile Suit Gundam'
when name like 'Modern Combat%' then 'Modern Combat'
when name like 'Monster Hunter%' then 'Monster Hunter'
when name like 'Monster Rancher%' then 'Monster Rancher'
when name like 'Mortal Kombat%' then 'Mortal Kombat'
when name like 'MotorStorm%' then 'MotorStorm'
when name like 'Mount & Blade%' then 'Mount & Blade'
when name like 'Might and Magic%' then 'Might and Magic'
when name like 'My Friend Pedro%' then 'My Friend Pedro'
when name like 'Myst%' then 'Myst'
when name like 'Mystery Case Files%' then 'Mystery Case Files'
when name like 'Nancy Drew%' then 'Nancy Drew'
when name like 'Naruto%' then 'Naruto'
when name like 'Need for Speed%' then 'Need for Speed'
when name like 'Might and Magic%' then 'Might and Magic'
when name like 'Oddworld%' then 'Oddworld'
when name like 'One Piece%' then 'One Piece'
when name like 'Onimusha%' then 'Onimusha'
when name like 'Pac-Man%' then 'Pac-Man'
when name like 'Persona%' then 'Persona'
when name like 'PokÃ©mon%' then 'Pokemon'
when name like 'Power Rangers%' then 'Power Rangers'
when name like 'Prince of Persia%' then 'Prince of Persia'
when name like 'Professor Layton%' then 'Professor Layton'
when name like 'Putt-Putt%' then 'Putt-Putt'
when name like 'Quest for Glory%' then 'Quest for Glory'
when name like 'Putt-Putt%' then 'Putt-Putt'
when name like 'Rainbow Six%' then 'Rainbow Six'
when name like 'Putt-Putt%' then 'Putt-Putt'
when name like 'Ratchet & Clank%' then 'Ratchet & Clank'
when name like 'Red Dead Redemption%' then 'Red Dead Redemption'
when name like 'Resident Evil%' then 'Resident Evil'
when name like 'Road Rash%' then 'Road Rash'
when name like 'RollerCoaster%' then 'RollerCoaster'
when name like 'Rusty Lake%' then 'Rusty Lake'
when name like 'Saints Row%' then 'Saints Row'
when name like 'Sam & Max%' then 'Sam & Max'
when name like 'Samurai Shodown%' then 'Samurai Shodown'
when name like 'Samurai Warriors%' then 'Samurai Warriors'
when name like 'Scooby-Doo%' then 'Scooby-Doo'
when name like 'Serious Sam%' then 'Serious Sam'
when name like 'Spider-Man%' then 'Spider-Man'
when name like 'Samurai Warriors%' then 'Samurai Warriors'
when name like 'Shadow Hearts%' then 'Shadow Hearts'
when name like 'Sherlock Holmes%' then 'Sherlock Holmes'
when name like 'Sleeping Dogs%' then 'Sleeping Dogs'
when name like 'South Park%' then 'South Park'
when name like 'Splatoon%' then 'Splatoon'
when name like 'SpongeBob SquarePants%' then 'SpongeBob SquarePants'
when name like 'Star Ocean%' then 'Star Ocean'
when name like 'Star Trek%' then 'Star Trek'
when name like 'Star Wars%' then 'Star Wars'
when name like 'Street Fighter%' then 'Street Fighter'
when name like 'Super Mario%' then 'Super Mario'
when name like 'Tales of Monkey Island%' then 'Tales of Monkey Island'
when name like 'Teenage Mutant Ninja Turtles%' then 'Teenage Mutant Ninja Turtles'
when name like 'The King of Fighters%' then 'The King of Fighters'
when name like 'The Legend of Heroes%' then 'The Legend of Heroes'
when name like 'The Legend of Zelda%' then 'The Legend of Zelda'
when name like 'The Room%' then 'The Room'
when name like 'The Simpsons%' then 'The Simpsons'
when name like 'The Walking Dead%' then 'The Walking Dead'
when name like 'Ultima%' then 'Ultima'
when name like 'Twisted Metal%' then 'Twisted Metal'
when name like 'Uncharted%' then 'Uncharted'
when name like 'Vader Immortal%' then 'Vader Immortal'
when name like 'Virtua Fighter%' then 'Virtua Fighter'
when name like 'Twisted Metal%' then 'Twisted Metal'
when name like 'WWE%' or name like 'WWF%' then 'WWE'
when name like 'Warhammer%' then 'Warhammer'
when name like 'Wing Commander%' then 'Wing Commander'
when name like 'Wolfenstein%' then 'Wolfenstein'
when name like 'World of Warcraft%' then 'World of Warcraft'
when name like 'X-Men%' then 'X-Men'
when name like 'Xenoblade Chronicles%' then 'Xenoblade Chronicles'
when name like 'Yakuza%' then 'Yakuza'
when name like 'Yu-Gi-Oh%' then 'Yu-Gi-Oh'
when name like 'Zombie Society%' then 'Zombie Society'
when name like 'Zone of the Enders%' then 'Zone of the Enders'
when name like 'inFamous%' then 'inFamous'


else name end as main_name
from
(
select * from videogame
where
rating is not null 
or votes is not null

) remove_null

where rating > (select avg(rating) from videogame where rating is not null or votes is not null)
and votes >  (select avg(votes) from videogame where rating is not null or votes is not null)

order by 1 asc

)
select
main_name,
(Action + adventure + Comedy + Crime + Family + Fantasy + Mystery + SciFi + Thriller) as distinct_generes

from (
select
main_name,
max(action) as action,
max(adventure) as adventure,
max(comedy) as comedy,
max(crime) as crime,
max(Family) as family,
max(Fantasy) as fantasy,
max(Mystery) as mystery,
max([Sci-Fi]) as scifi,
max(Thriller) as thriller
from
(
select
main_name,
name,
Action,
Adventure,
Comedy,
Crime,
Family,
Fantasy,
Mystery,
[Sci-Fi],
Thriller
from master_data
group by 2
)
group by 1
)
''';

    
df_sql = pd.read_sql_query(sql,con=engine)
df_sql.head()

                                           main_name  distinct_generes
0  'Goodbye, Galaxy!' Episode IV: Secret of the O...                 3
1  'Goodbye, Galaxy!' Episode V: The Armageddon M...                 3
2                                        .hack//G.U.                 2
3                                        11.22.63 VR                 2
4                                       13 Sentinels                 2

## playground query

In [27]:
## playground query 

sql='''

with master_data as
(
select
*,
case 
when name like 'Goodbye, Galaxy!%' then 'Goodbye, Galaxy!'
when name like '.hack//%' then '.hack//G.U.'
when name like '13 Sentinels%' then '13 Sentinels'
when name like '3D Pinball for Windows%' then '3D Pinball for Windows'
when name like '80 Days:%' then '80 Days'
when name like 'AI: The Somnium Files%' then 'AI: The Somnium Files'
when name like 'Accounting%' then 'Accounting'
when name like 'Ace Attorney%' then 'Ace Attorney'
when name like 'Ace Combat%' then 'Ace Combat'
when name like 'ActRaiser%' then 'ActRaiser'
when name like 'Advance Wars%' then 'Advance Wars'
when name like 'Adventure%' then 'Adventure'
when name like 'Agatha Christie%' then 'Agatha Christie'
when name like 'Age of Empires%' then 'Age of Empires'
when name like 'Age of Wonders%' then 'Age of Wonders'
when name like 'Adventure%' then 'Adventure'
when name like 'Aladdin%' then 'Aladdin'
when name like 'Alan Wake%' then 'Alan Wake'
when name like 'Alien%' then 'Alien'
when name like 'Aliens%' then 'Aliens'
when name like 'Alone in the Dark%' then 'Alone in the Dark'
when name like 'Alpha%' then 'Alpha'
when name like 'Alter%' then 'Alter'
when name like 'Alto%' then 'Alto'
when name like 'Angry Birds%' then 'Angry Birds'
when name like 'Animal%' then 'Animal'
when name like 'Animaniacs%' then 'Animaniacs'
when name like 'Ape Escape%' then 'Ape Escape'
when name like 'Arc the Lad%' then 'Arc the Lad'
when name like 'Ariel%' then 'Ariel'
when name like 'ArmA%' then 'ArmA'
when name like 'Army Men%' then 'Army Men'
when name like 'Asheron%' then 'Asheron Call'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Assassin%' and name like '%Creed%' then 'Assassin Creed'
when name like 'Atelier Iris%' then 'Atelier Iris'
when name like 'Atlantis%'  then 'Atlantis'
when name like 'Attack on Titan%' then 'Attack on Titan'
when name like 'Avatar%' then 'Avatar'
when name like 'Back to the Future%' then 'Back to the Future'
when name like 'Badland%' then 'Badland'
when name like 'Bakugan%' then 'Bakugan'
when name like 'Baldur%' and name like '%Gate%' then 'Baldur Gate'
when name like 'Barbie%' then 'Barbie'
when name like 'Baten Kaitos%' then 'Baten Kaitos'
when name like 'Battalion Wars%' then 'Battalion Wars'
when name like 'Battlestations%' then 'Battlestations Midway'
when name like '%Battletoads%' then 'Battletoads'
when name like '%Battletoads  Double Dragon%' then 'Battletoads Double Dragon'
when name like '%Battlezone%' then 'Battlezone'
when name like '%Bayonetta & Vanquish 10th Anniversary Bundle%' then 'Bayonetta'
when name like '%Bayonetta 2%' then 'Bayonetta'
when name like '%BeamNG.drive%' then 'BeamNG.drive'
when name like '%Bear in the Big Blue House: Bear Sense of Adventure%' then 'Bear in the Big Blue House: Bear Sense of Adventure'
when name like 'Bear with Me%' then 'Bear with Me'
when name like '%Beat Down: Fists of Vengeance%' then 'Beat Down: Fists of Vengeance'
when name like '%Beautiful Katamari%' then 'Beautiful Katamari'
when name like '%Beavis and Butt-Head%' then 'Beavis and Butt-Head'
when name like 'Beholder%' then 'Beholder'
when name like '%Bendy and the Ink Machine%' then 'Bendy and the Ink Machine'
when name like 'Beyond%' then 'Beyond'
when name like '%BioShock%' then 'BioShock'
when name like '%Black Mirror%' then 'Black Mirror'
when name like 'BlazBlue%' then 'BlazBlue'
when name like 'Blazing Angels%' then 'Blazing Angels'
when name like 'Bloody Roar%' then 'Bloody Roar'
when name like 'Boktai%' then 'Boktai'
when name like 'Bomberman%' then 'Bomberman'
when name like 'Bone%' then 'Bone'
when name like 'Borderlands%' then 'Borderlands'
when name like 'Bloodstained%' then 'Bloodstained'
when name like 'Broken Sword%' then 'Broken Sword'
when name like 'Brothers in Arms%' then 'Brothers in Arms'
when name like 'Buffy the Vampire Slayer%' then 'Buffy the Vampire Slayer'
when name like 'Bugs Bunny%' then 'Bugs Bunny'
when name like 'Bushido Blade%' then 'Bushido Blade'
when name like 'Burnout%' then 'Burnout'
when name like 'CR%' then 'CR'
when name like 'CSI%' then 'CSI'
when name like 'Cadillacs and Dinosaurs%' then 'Cadillacs and Dinosaurs'
when name like 'Call of Duty%' then 'Call of Duty'
when name like 'Call of Juarez%' then 'Call of Juarez'
when name like 'Capcom vs SNK%' then 'Capcom vs SNK'
when name like 'Cat Quest%' then 'Cat Quest'
when name like 'Chaos Rings%' then 'Chaos Rings'
when name like 'Chicken Invaders%' then 'Chicken Invaders'
when name like 'Chip Dale%' then 'Chip Dale'
when name like 'Chivalry%' then 'Chivalry'
when name like 'Close Combat%' then 'Close Combat'
when name like 'Colony Wars%' then 'Colony Wars'
when name like 'Command & Conquer%' then 'Command & Conquer'
when name like 'Castlevania%' then 'Castlevania'
when name like 'Commandos%' then 'Commandos'
when name like 'Castlevania%' then 'Castlevania'
when name like 'Crash Bandicoot%' then 'Crash Bandicoot'
when name like 'Castlevania%' then 'Castlevania'
when name like 'Cube Escape%' then 'Cube Escape'
when name like 'Crysis%' then 'Crysis'
when name like 'Danganronpa%' then 'Danganronpa'
when name like 'Dark Souls%' then 'Dark Souls'
when name like 'Darksiders%' then 'Darksiders'
when name like 'Dead Island%' then 'Dead Island'
when name like 'Dead Space%' then 'Dead Space'
when name like 'Dead or Alive%' then 'Dead or Alive'
when name like 'Deadpool%' then 'Deadpool'
when name like 'Demolition Man%' then 'Demolition Man'
when name like 'Demon Slayer%' then 'Demon Slayer'
when name like 'Descent%' then 'Descent'
when name like 'Deus Ex%' then 'Deus Ex'
when name like 'Devil May Cry%' then 'Devil May Cry'
when name like 'Diablo%' then 'Diablo'
when name like 'Die Hard%' then 'Die Hard'
when name like 'Disciples%' then 'Disciples'
when name like 'Die Hard%' then 'Die Hard'
when name like 'Disgaea%' then 'Disgaea'
when name like 'Dishonored%' then 'Dishonored'
when name like 'Dissidia%' then 'Dissidia'
when name like 'Disney%' then 'Disney'
when name like 'Divinity%' then 'Divinity'
when name like 'Doctor Who%' then 'Doctor Who'
when name like 'Dont Escape%' then 'Dont Escape'
when name like 'Disney%' then 'Disney'
when name like 'Donkey Kong%' then 'Donkey Kong'
when name like 'Doom%' then 'Doom'
when name like 'Double Dragon%' then 'Double Dragon'
when name like 'Dracula%' then 'Dracula'
when name like 'Dragon Age%' then 'Dragon Age'
when name like 'Dragon Ball%' then 'Dragon Ball'
when name like 'Dragon Warrior%' then 'Dragon Warrior'
when name like 'Drakengard%' then 'Drakengard'
when name like 'Duke Nukem%' then 'Duke Nukem'
when name like 'Dungeon%' then 'Dungeon'
when name like 'Dragon Quest%' then 'Dragon Quest'
when name like 'Dynasty Warriors%' then 'Dynasty Warriors'
when name like 'Dragon Quest%' then 'Dragon Quest'
when name like 'Earthworm%' then 'Earthworm'
when name like 'Evil Dead%' then 'Evil Dead'
when name like 'F.E.A.R.%' then 'F.E.A.R.'
when name like 'Fable%' then 'Fable'
when name like 'Dragon Quest%' then 'Dragon Quest'
when name like 'Fallout%' then 'Fallout'
when name like 'Far Cry%' then 'Far Cry'
when name like 'Fatal Frame%' then 'Fatal Frame'
when name like 'Final Fantasy%' then 'Final Fantasy'
when name like 'Fire Emblem%' then 'Fire Emblem'
when name like 'Forza Horizon%' then 'Forza Horizon'
when name like 'Forza Motorsport%' then 'Forza Motorsport'
when name like 'Freddi Fish%' then 'Freddi Fish'
when name like 'Front Mission%' then 'Front Mission'
when name like 'Fullmetal Alchemist%' then 'Fullmetal Alchemist'
when name like 'G.I. Joe%' then 'G.I. Joe'
when name like 'Ghost Recon%' then 'Ghost Recon'
when name like 'Ghost in the Shell%' then 'Ghost in the Shell'
when name like 'God of War%' then 'God of War'
when name like 'Goosebumps%' then 'Goosebumps'
when name like 'Gothic%' then 'Gothic'
when name like 'God of War%' then 'God of War'
when name like 'Grand Theft Auto%' then 'Grand Theft Auto'
when name like 'Gravity Rush%' then 'Gravity Rush'
when name like 'Growlanser%' then 'Growlanser'
when name like 'Guild Wars%' then 'Guild Wars'
when name like 'Guilty Gear%' then 'Guilty Gear'
when name like 'Halo%' then 'Halo'
when name like 'Hatsune Miku%' then 'Hatsune Miku'
when name like 'Heroes of Might and Magic%' then 'Heroes of Might and Magic'
when name like 'Hyperdimension Neptunia%' then 'Hitman'
when name like 'Indiana Jones%' then 'Indiana Jones'
when name like 'Infinity Blade%' then 'Infinity Blade'
when name like 'James Bond 007%' then 'James Bond 007'
when name like 'JoJos Bizarre Adventure%' then 'JoJos Bizarre Adventure'
when name like 'Jurassic%' then 'Jurassic World'
when name like 'Kings Quest%' then 'Kings Quest'
when name like 'Kingdom Hearts%' then 'Kingdom Hearts'
when name like 'Hitman%' then 'Hitman'
when name like 'Kirby%' then 'Kirby'
when name like 'Lands of Lore%' then 'Lands of Lore'
when name like 'Hitman%' then 'Hitman'
when name like 'Lego%' then 'Lego'
when name like 'Leisure Suit%' then 'Leisure Suit'
when name like 'Luigis Mansion%' then 'Luigis Mansion'
when name like 'Mafia%' then 'Mafia'
when name like 'Mario & Luigi%' then 'Mario & Luigi'
when name like 'Mario Party%' then 'Mario Party'
when name like 'Marvel%' then 'Marvel'
when name like 'Mass Effect%' then 'Mass Effect'
when name like 'Mech Commander%' then 'Mech Commander'
when name like 'MechWarrior%' then 'MechWarrior'
when name like 'Medal of Honor%' then 'Medal of Honor'
when name like 'Mega Man%' then 'Mega Man'
when name like 'Metal Gear%' then 'Metal Gear'
when name like 'Metal Slug%' then 'Metal Slug'
when name like 'Middle-Earth%' then 'Middle-Earth'
when name like 'Might and Magic%' then 'Might and Magic'
when name like 'Mobile Suit Gundam%' then 'Mobile Suit Gundam'
when name like 'Modern Combat%' then 'Modern Combat'
when name like 'Monster Hunter%' then 'Monster Hunter'
when name like 'Monster Rancher%' then 'Monster Rancher'
when name like 'Mortal Kombat%' then 'Mortal Kombat'
when name like 'MotorStorm%' then 'MotorStorm'
when name like 'Mount & Blade%' then 'Mount & Blade'
when name like 'Might and Magic%' then 'Might and Magic'
when name like 'My Friend Pedro%' then 'My Friend Pedro'
when name like 'Myst%' then 'Myst'
when name like 'Mystery Case Files%' then 'Mystery Case Files'
when name like 'Nancy Drew%' then 'Nancy Drew'
when name like 'Naruto%' then 'Naruto'
when name like 'Need for Speed%' then 'Need for Speed'
when name like 'Might and Magic%' then 'Might and Magic'
when name like 'Oddworld%' then 'Oddworld'
when name like 'One Piece%' then 'One Piece'
when name like 'Onimusha%' then 'Onimusha'
when name like 'Pac-Man%' then 'Pac-Man'
when name like 'Persona%' then 'Persona'
when name like 'PokÃ©mon%' then 'Pokemon'
when name like 'Power Rangers%' then 'Power Rangers'
when name like 'Prince of Persia%' then 'Prince of Persia'
when name like 'Professor Layton%' then 'Professor Layton'
when name like 'Putt-Putt%' then 'Putt-Putt'
when name like 'Quest for Glory%' then 'Quest for Glory'
when name like 'Putt-Putt%' then 'Putt-Putt'
when name like 'Rainbow Six%' then 'Rainbow Six'
when name like 'Putt-Putt%' then 'Putt-Putt'
when name like 'Ratchet & Clank%' then 'Ratchet & Clank'
when name like 'Red Dead Redemption%' then 'Red Dead Redemption'
when name like 'Resident Evil%' then 'Resident Evil'
when name like 'Road Rash%' then 'Road Rash'
when name like 'RollerCoaster%' then 'RollerCoaster'
when name like 'Rusty Lake%' then 'Rusty Lake'
when name like 'Saints Row%' then 'Saints Row'
when name like 'Sam & Max%' then 'Sam & Max'
when name like 'Samurai Shodown%' then 'Samurai Shodown'
when name like 'Samurai Warriors%' then 'Samurai Warriors'
when name like 'Scooby-Doo%' then 'Scooby-Doo'
when name like 'Serious Sam%' then 'Serious Sam'
when name like 'Samurai Warriors%' then 'Samurai Warriors'
when name like 'Shadow Hearts%' then 'Shadow Hearts'
when name like 'Sherlock Holmes%' then 'Sherlock Holmes'
when name like 'Sleeping Dogs%' then 'Sleeping Dogs'
when name like 'South Park%' then 'South Park'
when name like 'Splatoon%' then 'Splatoon'
when name like 'Spider-Man%' then 'Spider-Man'
when name like 'SpongeBob SquarePants%' then 'SpongeBob SquarePants'
when name like 'Star Ocean%' then 'Star Ocean'
when name like 'Star Trek%' then 'Star Trek'
when name like 'Star Wars%' then 'Star Wars'
when name like 'Street Fighter%' then 'Street Fighter'
when name like 'Super Mario%' then 'Super Mario'
when name like 'Tales of Monkey Island%' then 'Tales of Monkey Island'
when name like 'Teenage Mutant Ninja Turtles%' then 'Teenage Mutant Ninja Turtles'
when name like 'The King of Fighters%' then 'The King of Fighters'
when name like 'The Legend of Heroes%' then 'The Legend of Heroes'
when name like 'The Legend of Zelda%' then 'The Legend of Zelda'
when name like 'The Room%' then 'The Room'
when name like 'The Simpsons%' then 'The Simpsons'
when name like 'The Walking Dead%' then 'The Walking Dead'
when name like 'Ultima%' then 'Ultima'
when name like 'Twisted Metal%' then 'Twisted Metal'
when name like 'Uncharted%' then 'Uncharted'
when name like 'Vader Immortal%' then 'Vader Immortal'
when name like 'Virtua Fighter%' then 'Virtua Fighter'
when name like 'Twisted Metal%' then 'Twisted Metal'
when name like 'WWE%' or name like 'WWF%' then 'WWE'
when name like 'Warhammer%' then 'Warhammer'
when name like 'Wing Commander%' then 'Wing Commander'
when name like 'Wolfenstein%' then 'Wolfenstein'
when name like 'World of Warcraft%' then 'World of Warcraft'
when name like 'X-Men%' then 'X-Men'
when name like 'Xenoblade Chronicles%' then 'Xenoblade Chronicles'
when name like 'Yakuza%' then 'Yakuza'
when name like 'Yu-Gi-Oh%' then 'Yu-Gi-Oh'
when name like 'Zombie Society%' then 'Zombie Society'
when name like 'Zone of the Enders%' then 'Zone of the Enders'
when name like 'inFamous%' then 'inFamous'


else name end as main_name
from
(
select * from videogame
where
rating is not null 
or votes is not null

) remove_null

where rating > (select avg(rating) from videogame where rating is not null or votes is not null)
and votes >  (select avg(votes) from videogame where rating is not null or votes is not null)

order by 1 asc

)

select
*
from master_data 

''';

    
df_sql = pd.read_sql_query(sql,con=engine)
df_sql.head(30)

,index,Unnamed: 0,name,url,year,certificate,rating,votes,plot,Action,Adventure,Comedy,Crime,Family,Fantasy,Mystery,Sci-Fi,Thriller,main_name
0,0,0,Spider-Man,https://www.imdb.com/title/tt5807780/?ref_=adv...,2018.0,T,9.2,"20,759","When a new villain threatens New York City, Pe...",1,1,0,0,0,1,0,0,0,Spider-Man
1,1,1,Red Dead Redemption II,https://www.imdb.com/title/tt6161168/?ref_=adv...,2018.0,M,9.7,"35,703",Amidst the decline of the Wild West at the tur...,1,1,0,1,0,0,0,0,0,Red Dead Redemption
2,2,2,Grand Theft Auto V,https://www.imdb.com/title/tt2103188/?ref_=adv...,2013.0,M,9.5,"59,986",Three very different criminals team up for a s...,1,0,0,1,0,0,0,0,0,Grand Theft Auto
3,3,3,God of War,https://www.imdb.com/title/tt5838588/?ref_=adv...,2018.0,M,9.6,"26,118","After wiping out the gods of Mount Olympus, Kr...",1,1,0,0,0,0,0,0,0,God of War
4,4,4,Uncharted 4: A Thief's End,https://www.imdb.com/title/tt3334704/?ref_=adv...,2016.0,T,9.5,"28,722",Thrown back into the dangerous underworld he'd...,1,1,0,0,0,0,0,0,0,Uncharted
5,5,5,The Last of Us: Part II,https://www.imdb.com/title/tt6298000/?ref_=adv...,2020.0,M,8.5,"30,460","Five years after the events of The Last of Us,...",1,1,0,0,0,0,0,0,0,The Last of Us: Part II
6,6,6,Horizon Forbidden West,https://www.imdb.com/title/tt12496904/?ref_=ad...,2022.0,T,9.2,"2,979",Aloy treks into an arcane region and faces new...,1,1,0,0,0,0,1,0,0,Horizon Forbidden West
7,7,7,The Last of Us,https://www.imdb.com/title/tt2140553/?ref_=adv...,2013.0,M,9.7,"60,590","In a hostile, post-pandemic world, Joel and El...",1,1,0,0,0,0,0,0,0,The Last of Us
8,8,8,Detroit: Become Human,https://www.imdb.com/title/tt5158314/?ref_=adv...,2018.0,M,9.2,"16,907",Take control of three androids in their quest ...,1,1,0,0,0,0,0,0,0,Detroit: Become Human
9,9,9,Death Stranding,https://www.imdb.com/title/tt5807606/?ref_=adv...,2019.0,M,8.8,"8,136",Deliveryman Sam Porter must travel across a ra...,1,1,0,0,0,0,0,0,0,Death Stranding
10,10,10,Ghost of Tsushima,https://www.imdb.com/title/tt7651352/?ref_=adv...,2020.0,M,9.3,"8,452","Set in 1274 on the Tsushima Island, the last s...",1,1,0,0,0,0,0,0,0,Ghost of Tsushima
11,11,11,Spider-Man: Miles Morales,https://www.imdb.com/title/tt12496734/?ref_=ad...,2020.0,T,8.5,"5,835","In this sequel of Marvel's Spider-Man (2018), ...",1,1,0,0,0,1,0,0,0,Spider-Man
12,12,12,Cyberpunk 2077,https://www.imdb.com/title/tt3810192/?ref_=adv...,2020.0,M,8.0,"8,118","In Night City, a mercenary known as V navigate...",1,0,0,1,0,0,0,0,0,Cyberpunk 2077
13,13,13,Uncharted: Drake's Fortune,https://www.imdb.com/title/tt1000777/?ref_=adv...,2007.0,T,8.5,"20,343","Treasure hunter Nathan Drake, embarks in the a...",1,1,0,0,0,1,0,0,0,Uncharted
14,14,14,Batman: Arkham Knight,https://www.imdb.com/title/tt3554580/?ref_=adv...,2015.0,M,9.0,"18,970","With his back against the wall, Batman turns t...",1,1,0,1,0,0,0,0,0,Batman: Arkham Knight
15,17,17,Grand Theft Auto: San Andreas,https://www.imdb.com/title/tt0383385/?ref_=adv...,2004.0,M,9.4,"39,629","A family tragedy prompts gangster Carl ""CJ"" Jo...",1,0,0,1,0,0,0,0,0,Grand Theft Auto
16,18,18,MultiVersus,https://www.imdb.com/title/tt16150204/?ref_=ad...,2022.0,T,7.8,244,A crossover fighting game featuring many diffe...,1,0,0,0,0,1,0,1,0,MultiVersus
17,19,19,Far Cry 3,https://www.imdb.com/title/tt2321297/?ref_=adv...,2012.0,M,8.9,"18,775","While skydiving, Jason Brody and his friends l...",1,1,0,0,0,0,0,0,0,Far Cry
18,20,20,Star Wars Jedi: Fallen Order,https://www.imdb.com/title/tt5691474/?ref_=adv...,2019.0,T,8.5,"11,316","Set shortly after Revenge of the Sith, the pla...",1,1,0,0,0,0,0,0,0,Star Wars
19,21,21,Elden Ring,https://www.imdb.com/title/tt10562854/?ref_=ad...,2022.0,M,9.5,"4,108",In a dark fantasy world created by Hidetaka Mi...,1,1,0,0,0,1,0,0,0,Elden Ring
20,22,22,Xenoblade Chronicles 3,https://www.imdb.com/title/tt18115292/?ref_=ad...,2022.0,T,9.0,84,"In the world of Aionios, two nations are locke...",1,1,0,0,0,1,0,0,0,Xenoblade Chronicles
21,23,23,Uncharted: The Nathan Drake Collection,https://www.imdb.com/title/tt5766946/?ref_=adv...,2015.0,T,9.4,"5,383",A remastered collection of Uncharted: Drake's ...,1,1,0,0,0,1,0,0,0,Uncharted
22,24,24,Assassin's Creed Valhalla,https://www.imdb.com/title/tt12235026/?ref_=ad...,2020.0,M,8.1,"4,072",England in the age of the Vikings is a fractur...,1,1,0,0,0,1,0,0,0,Assassin Creed
23,25,25,Marvel's Guardians of the Galaxy,https://www.imdb.com/title/tt14844718/?ref_=ad...,2021.0,T,8.7,"3,381",After an epic conflict known as the Galactic W...,1,1,1,0,0,0,0,0,0,Marvel
24,26,26,Grand Theft Auto: Vice City,https://www.imdb.com/title/tt0314123/?ref_=adv...,2002.0,M,9.2,"26,397","After being released from jail, Tommy Vercetti...",1,0,0,1,0,0,0,0,0,Grand Theft Auto
25,27,27,Uncharted 2: Among Thieves,https://www.imdb.com/title/tt1349460/?ref_=adv...,2009.0,T,9.4,"25,048","After being tracked down by Harry Flynn, Natha...",1,1,0,0,0,1,0,0,0,Uncharted
26,28,28,The Witcher 3: Wild Hunt,https://www.imdb.com/title/tt2993508/?ref_=adv...,2015.0,M,9.7,"26,083",A monster hunter for hire embarks on an epic j...,1,1,0,0,0,0,0,0,0,The Witcher 3: Wild Hunt
27,29,29,Fallout: New Vegas,https://www.imdb.com/title/tt1706601/?ref_=adv...,2010.0,M,8.9,"12,296","After surviving a bullet to the head, Courier ...",1,1,0,0,0,0,0,1,0,Fallout
28,30,30,Command & Conquer: Red Alert 3,https://www.imdb.com/title/tt1198194/?ref_=adv...,2008.0,T,7.5,"2,066",As the Soviet Union was beginning to face defe...,1,0,0,0,0,0,0,1,0,Command & Conquer
29,31,31,Horizon Zero Dawn,https://www.imdb.com/title/tt4044024/?ref_=adv...,2017.0,T,9.0,"14,234","In a primitive tribal world where strange, mon...",1,1,0,0,0,0,1,0,0,Horizon Zero Dawn

*Observation:*

* There are 3377 equal columns 4122 based on votes
* There 1711 equal columns after ranking based on votes,avg rating
* There 1697  columns after ranking based on votes,avg rating, tenure
* After cleaning up the ranking logic where are at 201 columns

Phase 1 :- Project (create a metrics card with all the mentioned KPIs)

Phase 2 :-

* Understand which games are having a positive plot vs negative plot

* What is the url vs name

* create a senitment analysis metrcis(for plot summary) with  python and view is as a metric in a r sql query.

* play around with the sentimental metrics

## Playground query with ranking

In [28]:
# playground query 2 for ranking

sql='''

with master_data as (

select *,
case 
when name like 'Goodbye, Galaxy!%' then 'Goodbye, Galaxy!'
when name like '.hack//%' then '.hack//G.U.'
when name like '13 Sentinels%' then '13 Sentinels'
when name like '3D Pinball for Windows%' then '3D Pinball for Windows'
when name like '80 Days:%' then '80 Days'
when name like 'AI: The Somnium Files%' then 'AI: The Somnium Files'
when name like 'Accounting%' then 'Accounting'
when name like 'Ace Attorney%' then 'Ace Attorney'
when name like 'Ace Combat%' then 'Ace Combat'
when name like 'ActRaiser%' then 'ActRaiser'
when name like 'Advance Wars%' then 'Advance Wars'
when name like 'Adventure%' then 'Adventure'
when name like 'Agatha Christie%' then 'Agatha Christie'
when name like 'Age of Empires%' then 'Age of Empires'
when name like 'Age of Wonders%' then 'Age of Wonders'
when name like 'Adventure%' then 'Adventure'
when name like 'Aladdin%' then 'Aladdin'
when name like 'Alan Wake%' then 'Alan Wake'
when name like 'Alien%' then 'Alien'
when name like 'Aliens%' then 'Aliens'
when name like 'Alone in the Dark%' then 'Alone in the Dark'
when name like 'Alpha%' then 'Alpha'
when name like 'Alter%' then 'Alter'
when name like 'Alto%' then 'Alto'
when name like 'Angry Birds%' then 'Angry Birds'
when name like 'Animal%' then 'Animal'
when name like 'Animaniacs%' then 'Animaniacs'
when name like 'Ape Escape%' then 'Ape Escape'
when name like 'Arc the Lad%' then 'Arc the Lad'
when name like 'Ariel%' then 'Ariel'
when name like 'ArmA%' then 'ArmA'
when name like 'Army Men%' then 'Army Men'
when name like 'Asheron%' then 'Asheron Call'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Assassin%' and name like '%Creed%' then 'Assassin Creed'
when name like 'Atelier Iris%' then 'Atelier Iris'
when name like 'Atlantis%'  then 'Atlantis'
when name like 'Attack on Titan%' then 'Attack on Titan'
when name like 'Avatar%' then 'Avatar'
when name like 'Back to the Future%' then 'Back to the Future'
when name like 'Badland%' then 'Badland'
when name like 'Bakugan%' then 'Bakugan'
when name like 'Baldur%' and name like '%Gate%' then 'Baldur Gate'
when name like 'Barbie%' then 'Barbie'
when name like 'Baten Kaitos%' then 'Baten Kaitos'
when name like 'Battalion Wars%' then 'Battalion Wars'
when name like 'Battlestations%' then 'Battlestations Midway'
when name like '%Battletoads%' then 'Battletoads'
when name like '%Battletoads  Double Dragon%' then 'Battletoads Double Dragon'
when name like '%Battlezone%' then 'Battlezone'
when name like '%Bayonetta & Vanquish 10th Anniversary Bundle%' then 'Bayonetta'
when name like '%Bayonetta 2%' then 'Bayonetta'
when name like '%BeamNG.drive%' then 'BeamNG.drive'
when name like '%Bear in the Big Blue House: Bear Sense of Adventure%' then 'Bear in the Big Blue House: Bear Sense of Adventure'
when name like 'Bear with Me%' then 'Bear with Me'
when name like '%Beat Down: Fists of Vengeance%' then 'Beat Down: Fists of Vengeance'
when name like '%Beautiful Katamari%' then 'Beautiful Katamari'
when name like '%Beavis and Butt-Head%' then 'Beavis and Butt-Head'
when name like 'Beholder%' then 'Beholder'
when name like '%Bendy and the Ink Machine%' then 'Bendy and the Ink Machine'
when name like 'Beyond%' then 'Beyond'
when name like '%BioShock%' then 'BioShock'
when name like '%Black Mirror%' then 'Black Mirror'
when name like 'BlazBlue%' then 'BlazBlue'
when name like 'Blazing Angels%' then 'Blazing Angels'
when name like 'Bloody Roar%' then 'Bloody Roar'
when name like 'Boktai%' then 'Boktai'
when name like 'Bomberman%' then 'Bomberman'
when name like 'Bone%' then 'Bone'
when name like 'Borderlands%' then 'Borderlands'
when name like 'Bloodstained%' then 'Bloodstained'
when name like 'Broken Sword%' then 'Broken Sword'
when name like 'Brothers in Arms%' then 'Brothers in Arms'
when name like 'Buffy the Vampire Slayer%' then 'Buffy the Vampire Slayer'
when name like 'Bugs Bunny%' then 'Bugs Bunny'
when name like 'Bushido Blade%' then 'Bushido Blade'
when name like 'Burnout%' then 'Burnout'
when name like 'CR%' then 'CR'
when name like 'CSI%' then 'CSI'
when name like 'Cadillacs and Dinosaurs%' then 'Cadillacs and Dinosaurs'
when name like 'Call of Duty%' then 'Call of Duty'
when name like 'Call of Juarez%' then 'Call of Juarez'
when name like 'Capcom vs SNK%' then 'Capcom vs SNK'
when name like 'Cat Quest%' then 'Cat Quest'
when name like 'Chaos Rings%' then 'Chaos Rings'
when name like 'Chicken Invaders%' then 'Chicken Invaders'
when name like 'Chip Dale%' then 'Chip Dale'
when name like 'Chivalry%' then 'Chivalry'
when name like 'Close Combat%' then 'Close Combat'
when name like 'Colony Wars%' then 'Colony Wars'
when name like 'Command & Conquer%' then 'Command & Conquer'
when name like 'Castlevania%' then 'Castlevania'
when name like 'Commandos%' then 'Commandos'
when name like 'Castlevania%' then 'Castlevania'
when name like 'Crash Bandicoot%' then 'Crash Bandicoot'
when name like 'Castlevania%' then 'Castlevania'
when name like 'Cube Escape%' then 'Cube Escape'
when name like 'Crysis%' then 'Crysis'
when name like 'Danganronpa%' then 'Danganronpa'
when name like 'Dark Souls%' then 'Dark Souls'
when name like 'Darksiders%' then 'Darksiders'
when name like 'Dead Island%' then 'Dead Island'
when name like 'Dead Space%' then 'Dead Space'
when name like 'Dead or Alive%' then 'Dead or Alive'
when name like 'Deadpool%' then 'Deadpool'
when name like 'Demolition Man%' then 'Demolition Man'
when name like 'Demon Slayer%' then 'Demon Slayer'
when name like 'Descent%' then 'Descent'
when name like 'Deus Ex%' then 'Deus Ex'
when name like 'Devil May Cry%' then 'Devil May Cry'
when name like 'Diablo%' then 'Diablo'
when name like 'Die Hard%' then 'Die Hard'
when name like 'Disciples%' then 'Disciples'
when name like 'Die Hard%' then 'Die Hard'
when name like 'Disgaea%' then 'Disgaea'
when name like 'Dishonored%' then 'Dishonored'
when name like 'Dissidia%' then 'Dissidia'
when name like 'Disney%' then 'Disney'
when name like 'Divinity%' then 'Divinity'
when name like 'Doctor Who%' then 'Doctor Who'
when name like 'Dont Escape%' then 'Dont Escape'
when name like 'Disney%' then 'Disney'
when name like 'Donkey Kong%' then 'Donkey Kong'
when name like 'Doom%' then 'Doom'
when name like 'Double Dragon%' then 'Double Dragon'
when name like 'Dracula%' then 'Dracula'
when name like 'Dragon Age%' then 'Dragon Age'
when name like 'Dragon Ball%' then 'Dragon Ball'
when name like 'Dragon Warrior%' then 'Dragon Warrior'
when name like 'Drakengard%' then 'Drakengard'
when name like 'Duke Nukem%' then 'Duke Nukem'
when name like 'Dungeon%' then 'Dungeon'
when name like 'Dragon Quest%' then 'Dragon Quest'
when name like 'Dynasty Warriors%' then 'Dynasty Warriors'
when name like 'Dragon Quest%' then 'Dragon Quest'
when name like 'Earthworm%' then 'Earthworm'
when name like 'Evil Dead%' then 'Evil Dead'
when name like 'F.E.A.R.%' then 'F.E.A.R.'
when name like 'Fable%' then 'Fable'
when name like 'Dragon Quest%' then 'Dragon Quest'
when name like 'Fallout%' then 'Fallout'
when name like 'Far Cry%' then 'Far Cry'
when name like 'Fatal Frame%' then 'Fatal Frame'
when name like 'Final Fantasy%' then 'Final Fantasy'
when name like 'Fire Emblem%' then 'Fire Emblem'
when name like 'Forza Horizon%' then 'Forza Horizon'
when name like 'Forza Motorsport%' then 'Forza Motorsport'
when name like 'Freddi Fish%' then 'Freddi Fish'
when name like 'Front Mission%' then 'Front Mission'
when name like 'Fullmetal Alchemist%' then 'Fullmetal Alchemist'
when name like 'G.I. Joe%' then 'G.I. Joe'
when name like 'Ghost Recon%' then 'Ghost Recon'
when name like 'Ghost in the Shell%' then 'Ghost in the Shell'
when name like 'God of War%' then 'God of War'
when name like 'Goosebumps%' then 'Goosebumps'
when name like 'Gothic%' then 'Gothic'
when name like 'God of War%' then 'God of War'
when name like 'Grand Theft Auto%' then 'Grand Theft Auto'
when name like 'Gravity Rush%' then 'Gravity Rush'
when name like 'Growlanser%' then 'Growlanser'
when name like 'Guild Wars%' then 'Guild Wars'
when name like 'Guilty Gear%' then 'Guilty Gear'
when name like 'Halo%' then 'Halo'
when name like 'Hatsune Miku%' then 'Hatsune Miku'
when name like 'Heroes of Might and Magic%' then 'Heroes of Might and Magic'
when name like 'Hyperdimension Neptunia%' then 'Hitman'
when name like 'Indiana Jones%' then 'Indiana Jones'
when name like 'Infinity Blade%' then 'Infinity Blade'
when name like 'James Bond 007%' then 'James Bond 007'
when name like 'JoJos Bizarre Adventure%' then 'JoJos Bizarre Adventure'
when name like 'Jurassic%' then 'Jurassic World'
when name like 'Kings Quest%' then 'Kings Quest'
when name like 'Kingdom Hearts%' then 'Kingdom Hearts'
when name like 'Hitman%' then 'Hitman'
when name like 'Kirby%' then 'Kirby'
when name like 'Lands of Lore%' then 'Lands of Lore'
when name like 'Hitman%' then 'Hitman'
when name like 'Lego%' then 'Lego'
when name like 'Leisure Suit%' then 'Leisure Suit'
when name like 'Luigis Mansion%' then 'Luigis Mansion'
when name like 'Mafia%' then 'Mafia'
when name like 'Mario & Luigi%' then 'Mario & Luigi'
when name like 'Mario Party%' then 'Mario Party'
when name like 'Marvel%' then 'Marvel'
when name like 'Mass Effect%' then 'Mass Effect'
when name like 'Mech Commander%' then 'Mech Commander'
when name like 'MechWarrior%' then 'MechWarrior'
when name like 'Medal of Honor%' then 'Medal of Honor'
when name like 'Mega Man%' then 'Mega Man'
when name like 'Metal Gear%' then 'Metal Gear'
when name like 'Metal Slug%' then 'Metal Slug'
when name like 'Middle-Earth%' then 'Middle-Earth'
when name like 'Might and Magic%' then 'Might and Magic'
when name like 'Mobile Suit Gundam%' then 'Mobile Suit Gundam'
when name like 'Modern Combat%' then 'Modern Combat'
when name like 'Monster Hunter%' then 'Monster Hunter'
when name like 'Monster Rancher%' then 'Monster Rancher'
when name like 'Mortal Kombat%' then 'Mortal Kombat'
when name like 'MotorStorm%' then 'MotorStorm'
when name like 'Mount & Blade%' then 'Mount & Blade'
when name like 'Might and Magic%' then 'Might and Magic'
when name like 'My Friend Pedro%' then 'My Friend Pedro'
when name like 'Myst%' then 'Myst'
when name like 'Mystery Case Files%' then 'Mystery Case Files'
when name like 'Nancy Drew%' then 'Nancy Drew'
when name like 'Naruto%' then 'Naruto'
when name like 'Need for Speed%' then 'Need for Speed'
when name like 'Might and Magic%' then 'Might and Magic'
when name like 'Oddworld%' then 'Oddworld'
when name like 'One Piece%' then 'One Piece'
when name like 'Onimusha%' then 'Onimusha'
when name like 'Pac-Man%' then 'Pac-Man'
when name like 'Persona%' then 'Persona'
when name like 'PokÃ©mon%' then 'Pokemon'
when name like 'Power Rangers%' then 'Power Rangers'
when name like 'Prince of Persia%' then 'Prince of Persia'
when name like 'Professor Layton%' then 'Professor Layton'
when name like 'Putt-Putt%' then 'Putt-Putt'
when name like 'Quest for Glory%' then 'Quest for Glory'
when name like 'Putt-Putt%' then 'Putt-Putt'
when name like 'Rainbow Six%' then 'Rainbow Six'
when name like 'Putt-Putt%' then 'Putt-Putt'
when name like 'Ratchet & Clank%' then 'Ratchet & Clank'
when name like 'Red Dead Redemption%' then 'Red Dead Redemption'
when name like 'Resident Evil%' then 'Resident Evil'
when name like 'Road Rash%' then 'Road Rash'
when name like 'RollerCoaster%' then 'RollerCoaster'
when name like 'Rusty Lake%' then 'Rusty Lake'
when name like 'Saints Row%' then 'Saints Row'
when name like 'Sam & Max%' then 'Sam & Max'
when name like 'Samurai Shodown%' then 'Samurai Shodown'
when name like 'Samurai Warriors%' then 'Samurai Warriors'
when name like 'Scooby-Doo%' then 'Scooby-Doo'
when name like 'Serious Sam%' then 'Serious Sam'
when name like 'Samurai Warriors%' then 'Samurai Warriors'
when name like 'Shadow Hearts%' then 'Shadow Hearts'
when name like 'Sherlock Holmes%' then 'Sherlock Holmes'
when name like 'Sleeping Dogs%' then 'Sleeping Dogs'
when name like 'South Park%' then 'South Park'
when name like 'Splatoon%' then 'Splatoon'
when name like 'SpongeBob SquarePants%' then 'SpongeBob SquarePants'
when name like 'Star Ocean%' then 'Star Ocean'
when name like 'Star Trek%' then 'Star Trek'
when name like 'Star Wars%' then 'Star Wars'
when name like 'Street Fighter%' then 'Street Fighter'
when name like 'Super Mario%' then 'Super Mario'
when name like 'Tales of Monkey Island%' then 'Tales of Monkey Island'
when name like 'Teenage Mutant Ninja Turtles%' then 'Teenage Mutant Ninja Turtles'
when name like 'The King of Fighters%' then 'The King of Fighters'
when name like 'The Legend of Heroes%' then 'The Legend of Heroes'
when name like 'The Legend of Zelda%' then 'The Legend of Zelda'
when name like 'The Room%' then 'The Room'
when name like 'The Simpsons%' then 'The Simpsons'
when name like 'The Walking Dead%' then 'The Walking Dead'
when name like 'Ultima%' then 'Ultima'
when name like 'Twisted Metal%' then 'Twisted Metal'
when name like 'Uncharted%' then 'Uncharted'
when name like 'Vader Immortal%' then 'Vader Immortal'
when name like 'Virtua Fighter%' then 'Virtua Fighter'
when name like 'Twisted Metal%' then 'Twisted Metal'
when name like 'WWE%' or name like 'WWF%' then 'WWE'
when name like 'Warhammer%' then 'Warhammer'
when name like 'Wing Commander%' then 'Wing Commander'
when name like 'Wolfenstein%' then 'Wolfenstein'
when name like 'World of Warcraft%' then 'World of Warcraft'
when name like 'X-Men%' then 'X-Men'
when name like 'Xenoblade Chronicles%' then 'Xenoblade Chronicles'
when name like 'Yakuza%' then 'Yakuza'
when name like 'Yu-Gi-Oh%' then 'Yu-Gi-Oh'
when name like 'Zombie Society%' then 'Zombie Society'
when name like 'Zone of the Enders%' then 'Zone of the Enders'
when name like 'inFamous%' then 'inFamous'


else name end as main_name
from 
(
select * from videogame
where
rating is not null 
or votes is not null
)

where rating > (select avg(rating) from videogame where rating is not null or votes is not null)
and votes >  (select avg(votes) from videogame where rating is not null or votes is not null)
)
select count(*)
from 
(
select
version.main_name,
version.count_version,
tenure_table.launch_year,
tenure_table.latest_year,
tenure_table.tenure,
tenure_table.last_ten_yrs_launched,
total_votes_table.total_votes,
rating.avg_rating,
rating.min_rating,
rating.max_rating,
rating_avg.rating_counts_greater_than_overall_avg,
count_of_versions_greater_than_avg_rating.total_games_greater_than_avg_rating,
cerifications.distinct_certifications,
generes.distinct_generes,
traffic.traffic_contribution,
row_number () over (order by total_votes_table.total_votes desc,rating.avg_rating desc,rating.min_rating desc,rating.max_rating desc,cerifications.distinct_certifications desc,generes.distinct_generes desc,version.count_version desc,rating_avg.rating_counts_greater_than_overall_avg desc) as row_number,
dense_rank () over (order by total_votes_table.total_votes desc,rating.avg_rating desc,rating.min_rating desc,rating.max_rating desc,cerifications.distinct_certifications desc,generes.distinct_generes desc, version.count_version desc,rating_avg.rating_counts_greater_than_overall_avg desc) as rank_number,
case 
when total_votes_table.total_votes =lag(total_votes_table.total_votes) over (order by total_votes_table.total_votes desc,rating.avg_rating desc,rating.min_rating desc,rating.max_rating desc,cerifications.distinct_certifications desc,generes.distinct_generes desc,version.count_version desc,rating_avg.rating_counts_greater_than_overall_avg desc)
and rating.avg_rating =lag(rating.avg_rating) over (order by total_votes_table.total_votes desc,rating.avg_rating desc,rating.min_rating desc,rating.max_rating desc,cerifications.distinct_certifications desc,generes.distinct_generes desc,version.count_version desc,rating_avg.rating_counts_greater_than_overall_avg desc)
and rating.min_rating =lag(rating.min_rating) over (order by total_votes_table.total_votes desc,rating.avg_rating desc,rating.min_rating desc,rating.max_rating desc,cerifications.distinct_certifications desc,generes.distinct_generes desc,version.count_version desc,rating_avg.rating_counts_greater_than_overall_avg desc)
and rating.max_rating =lag(rating.max_rating) over (order by total_votes_table.total_votes desc,rating.avg_rating desc,rating.min_rating desc,rating.max_rating desc,cerifications.distinct_certifications desc,generes.distinct_generes desc,version.count_version desc, rating_avg.rating_counts_greater_than_overall_avg desc)
and cerifications.distinct_certifications =lag(cerifications.distinct_certifications) over (order by total_votes_table.total_votes desc,rating.avg_rating desc,rating.min_rating desc,rating.max_rating desc,cerifications.distinct_certifications desc,generes.distinct_generes desc,version.count_version desc,rating_avg.rating_counts_greater_than_overall_avg desc)
and generes.distinct_generes =lag(generes.distinct_generes) over (order by total_votes_table.total_votes desc,rating.avg_rating desc,rating.min_rating desc,rating.max_rating desc,cerifications.distinct_certifications desc,generes.distinct_generes desc,version.count_version desc,rating_avg.rating_counts_greater_than_overall_avg desc)
then 'equal' else 'not equal' end as flag

from (
select
main_name,
count(name) as count_version
from master_data
group by 1) version

join (
select
main_name,
launch_year,
latest_year,
case when tenure = 0 then 1 else tenure end as tenure,
case when launch_year >= 2012 and latest_year <= 2022 then 'Yes' else 'No' end as last_ten_yrs_launched
from
(
select
main_name,
min(year) as launch_year,
max(year) as latest_year,
max(year)-min(year) as tenure
from master_data
group by 1
)

) tenure_table on version.main_name=tenure_table.main_name

join (

select
main_name,
sum(votes) as total_votes
from master_data
group by 1

) total_votes_table on version.main_name=total_votes_table.main_name


join (

select
main_name,
round(avg(rating),2) as avg_rating,
min(rating) as min_rating,
max(rating) as max_rating
from master_data
group by 1

) rating on version.main_name=rating.main_name

join (

select
main_name,
count(rating) as rating_counts_greater_than_overall_avg
from (
select
main_name,
rating,
round((select avg(rating) from master_data),2) as avg_rating
from master_data
where rating > avg_rating
group by 1,2
)
group by 1


) rating_avg on version.main_name=rating_avg.main_name

join (

select
main_name,
sum(greater_than_avg_rating) as total_games_greater_than_avg_rating
from

(
select
main_name,
name,
rating,
round((select avg(rating) from master_data),2) as avg_rating,
case when rating > round((select avg(rating) from master_data),2) then 1 else 0 end as greater_than_avg_rating
from master_data 
group by 1,2
)
group by 1

) count_of_versions_greater_than_avg_rating on version.main_name=count_of_versions_greater_than_avg_rating.main_name

join (

select
main_name,
count(distinct certificate) as distinct_certifications
from
(
select
distinct
main_name,
name,
certificate
from master_data
group by 1,2
)
group by 1

) cerifications on version.main_name=cerifications.main_name

join (

select
main_name,
(Action + adventure + Comedy + Crime + Family + Fantasy + Mystery + SciFi + Thriller) as distinct_generes

from (
select
main_name,
max(action) as action,
max(adventure) as adventure,
max(comedy) as comedy,
max(crime) as crime,
max(Family) as family,
max(Fantasy) as fantasy,
max(Mystery) as mystery,
max([Sci-Fi]) as scifi,
max(Thriller) as thriller
from
(
select
main_name,
name,
Action,
Adventure,
Comedy,
Crime,
Family,
Fantasy,
Mystery,
[Sci-Fi],
Thriller
from master_data
group by 2
)
group by 1
)


)  generes on version.main_name=generes.main_name

join (

select
main_name,
sum(votes)/(select sum(votes) from master_data) as traffic_contribution
from master_data
group by 1


) traffic on version.main_name=traffic.main_name

order by rank_number asc
)
where flag='equal'
''';

    
df_sql = pd.read_sql_query(sql,con=engine)
df_sql.head()

   count(*)
0       201

## Master Query for Phase 1

In [30]:
## Master query for Phase 1 in the project!!!

## this is the final query that has all the metrics that we want as a scorecard with the ranking logic applied 
## if 2 metrics are in the ranking system, then another metric will be compared to evaulate and derive the rank
## for example if the votes of name 1 and 2 are same, then avg_rating 1 and 2 will compared, if avg_rating 1 and 2 are same then tenure is compared and etc


sql='''

with master_data as (

select *,
case 
when name like 'Goodbye, Galaxy!%' then 'Goodbye, Galaxy!'
when name like '.hack//%' then '.hack//G.U.'
when name like '13 Sentinels%' then '13 Sentinels'
when name like '3D Pinball for Windows%' then '3D Pinball for Windows'
when name like '80 Days:%' then '80 Days'
when name like 'AI: The Somnium Files%' then 'AI: The Somnium Files'
when name like 'Accounting%' then 'Accounting'
when name like 'Ace Attorney%' then 'Ace Attorney'
when name like 'Ace Combat%' then 'Ace Combat'
when name like 'ActRaiser%' then 'ActRaiser'
when name like 'Advance Wars%' then 'Advance Wars'
when name like 'Adventure%' then 'Adventure'
when name like 'Agatha Christie%' then 'Agatha Christie'
when name like 'Age of Empires%' then 'Age of Empires'
when name like 'Age of Wonders%' then 'Age of Wonders'
when name like 'Adventure%' then 'Adventure'
when name like 'Aladdin%' then 'Aladdin'
when name like 'Alan Wake%' then 'Alan Wake'
when name like 'Alien%' then 'Alien'
when name like 'Aliens%' then 'Aliens'
when name like 'Alone in the Dark%' then 'Alone in the Dark'
when name like 'Alpha%' then 'Alpha'
when name like 'Alter%' then 'Alter'
when name like 'Alto%' then 'Alto'
when name like 'Angry Birds%' then 'Angry Birds'
when name like 'Animal%' then 'Animal'
when name like 'Animaniacs%' then 'Animaniacs'
when name like 'Ape Escape%' then 'Ape Escape'
when name like 'Arc the Lad%' then 'Arc the Lad'
when name like 'Ariel%' then 'Ariel'
when name like 'ArmA%' then 'ArmA'
when name like 'Army Men%' then 'Army Men'
when name like 'Asheron%' then 'Asheron Call'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Assassin%' and name like '%Creed%' then 'Assassin Creed'
when name like 'Atelier Iris%' then 'Atelier Iris'
when name like 'Atlantis%'  then 'Atlantis'
when name like 'Attack on Titan%' then 'Attack on Titan'
when name like 'Avatar%' then 'Avatar'
when name like 'Back to the Future%' then 'Back to the Future'
when name like 'Badland%' then 'Badland'
when name like 'Bakugan%' then 'Bakugan'
when name like 'Baldur%' and name like '%Gate%' then 'Baldur Gate'
when name like 'Barbie%' then 'Barbie'
when name like 'Baten Kaitos%' then 'Baten Kaitos'
when name like 'Battalion Wars%' then 'Battalion Wars'
when name like 'Battlestations%' then 'Battlestations Midway'
when name like '%Battletoads%' then 'Battletoads'
when name like '%Battletoads  Double Dragon%' then 'Battletoads Double Dragon'
when name like '%Battlezone%' then 'Battlezone'
when name like '%Bayonetta & Vanquish 10th Anniversary Bundle%' then 'Bayonetta'
when name like '%Bayonetta 2%' then 'Bayonetta'
when name like '%BeamNG.drive%' then 'BeamNG.drive'
when name like '%Bear in the Big Blue House: Bear Sense of Adventure%' then 'Bear in the Big Blue House: Bear Sense of Adventure'
when name like 'Bear with Me%' then 'Bear with Me'
when name like '%Beat Down: Fists of Vengeance%' then 'Beat Down: Fists of Vengeance'
when name like '%Beautiful Katamari%' then 'Beautiful Katamari'
when name like '%Beavis and Butt-Head%' then 'Beavis and Butt-Head'
when name like 'Beholder%' then 'Beholder'
when name like '%Bendy and the Ink Machine%' then 'Bendy and the Ink Machine'
when name like 'Beyond%' then 'Beyond'
when name like '%BioShock%' then 'BioShock'
when name like '%Black Mirror%' then 'Black Mirror'
when name like 'BlazBlue%' then 'BlazBlue'
when name like 'Blazing Angels%' then 'Blazing Angels'
when name like 'Bloody Roar%' then 'Bloody Roar'
when name like 'Boktai%' then 'Boktai'
when name like 'Bomberman%' then 'Bomberman'
when name like 'Bone%' then 'Bone'
when name like 'Borderlands%' then 'Borderlands'
when name like 'Bloodstained%' then 'Bloodstained'
when name like 'Broken Sword%' then 'Broken Sword'
when name like 'Brothers in Arms%' then 'Brothers in Arms'
when name like 'Buffy the Vampire Slayer%' then 'Buffy the Vampire Slayer'
when name like 'Bugs Bunny%' then 'Bugs Bunny'
when name like 'Bushido Blade%' then 'Bushido Blade'
when name like 'Burnout%' then 'Burnout'
when name like 'CR%' then 'CR'
when name like 'CSI%' then 'CSI'
when name like 'Cadillacs and Dinosaurs%' then 'Cadillacs and Dinosaurs'
when name like 'Call of Duty%' then 'Call of Duty'
when name like 'Call of Juarez%' then 'Call of Juarez'
when name like 'Capcom vs SNK%' then 'Capcom vs SNK'
when name like 'Cat Quest%' then 'Cat Quest'
when name like 'Chaos Rings%' then 'Chaos Rings'
when name like 'Chicken Invaders%' then 'Chicken Invaders'
when name like 'Chip Dale%' then 'Chip Dale'
when name like 'Chivalry%' then 'Chivalry'
when name like 'Close Combat%' then 'Close Combat'
when name like 'Colony Wars%' then 'Colony Wars'
when name like 'Command & Conquer%' then 'Command & Conquer'
when name like 'Castlevania%' then 'Castlevania'
when name like 'Commandos%' then 'Commandos'
when name like 'Castlevania%' then 'Castlevania'
when name like 'Crash Bandicoot%' then 'Crash Bandicoot'
when name like 'Castlevania%' then 'Castlevania'
when name like 'Cube Escape%' then 'Cube Escape'
when name like 'Crysis%' then 'Crysis'
when name like 'Danganronpa%' then 'Danganronpa'
when name like 'Dark Souls%' then 'Dark Souls'
when name like 'Darksiders%' then 'Darksiders'
when name like 'Dead Island%' then 'Dead Island'
when name like 'Dead Space%' then 'Dead Space'
when name like 'Dead or Alive%' then 'Dead or Alive'
when name like 'Deadpool%' then 'Deadpool'
when name like 'Demolition Man%' then 'Demolition Man'
when name like 'Demon Slayer%' then 'Demon Slayer'
when name like 'Descent%' then 'Descent'
when name like 'Deus Ex%' then 'Deus Ex'
when name like 'Devil May Cry%' then 'Devil May Cry'
when name like 'Diablo%' then 'Diablo'
when name like 'Die Hard%' then 'Die Hard'
when name like 'Disciples%' then 'Disciples'
when name like 'Die Hard%' then 'Die Hard'
when name like 'Disgaea%' then 'Disgaea'
when name like 'Dishonored%' then 'Dishonored'
when name like 'Dissidia%' then 'Dissidia'
when name like 'Disney%' then 'Disney'
when name like 'Divinity%' then 'Divinity'
when name like 'Doctor Who%' then 'Doctor Who'
when name like 'Dont Escape%' then 'Dont Escape'
when name like 'Disney%' then 'Disney'
when name like 'Donkey Kong%' then 'Donkey Kong'
when name like 'Doom%' then 'Doom'
when name like 'Double Dragon%' then 'Double Dragon'
when name like 'Dracula%' then 'Dracula'
when name like 'Dragon Age%' then 'Dragon Age'
when name like 'Dragon Ball%' then 'Dragon Ball'
when name like 'Dragon Warrior%' then 'Dragon Warrior'
when name like 'Drakengard%' then 'Drakengard'
when name like 'Duke Nukem%' then 'Duke Nukem'
when name like 'Dungeon%' then 'Dungeon'
when name like 'Dragon Quest%' then 'Dragon Quest'
when name like 'Dynasty Warriors%' then 'Dynasty Warriors'
when name like 'Dragon Quest%' then 'Dragon Quest'
when name like 'Earthworm%' then 'Earthworm'
when name like 'Evil Dead%' then 'Evil Dead'
when name like 'F.E.A.R.%' then 'F.E.A.R.'
when name like 'Fable%' then 'Fable'
when name like 'Dragon Quest%' then 'Dragon Quest'
when name like 'Fallout%' then 'Fallout'
when name like 'Far Cry%' then 'Far Cry'
when name like 'Fatal Frame%' then 'Fatal Frame'
when name like 'Final Fantasy%' then 'Final Fantasy'
when name like 'Fire Emblem%' then 'Fire Emblem'
when name like 'Forza Horizon%' then 'Forza Horizon'
when name like 'Forza Motorsport%' then 'Forza Motorsport'
when name like 'Freddi Fish%' then 'Freddi Fish'
when name like 'Front Mission%' then 'Front Mission'
when name like 'Fullmetal Alchemist%' then 'Fullmetal Alchemist'
when name like 'G.I. Joe%' then 'G.I. Joe'
when name like 'Ghost Recon%' then 'Ghost Recon'
when name like 'Ghost in the Shell%' then 'Ghost in the Shell'
when name like 'God of War%' then 'God of War'
when name like 'Goosebumps%' then 'Goosebumps'
when name like 'Gothic%' then 'Gothic'
when name like 'God of War%' then 'God of War'
when name like 'Grand Theft Auto%' then 'Grand Theft Auto'
when name like 'Gravity Rush%' then 'Gravity Rush'
when name like 'Growlanser%' then 'Growlanser'
when name like 'Guild Wars%' then 'Guild Wars'
when name like 'Guilty Gear%' then 'Guilty Gear'
when name like 'Halo%' then 'Halo'
when name like 'Hatsune Miku%' then 'Hatsune Miku'
when name like 'Heroes of Might and Magic%' then 'Heroes of Might and Magic'
when name like 'Hyperdimension Neptunia%' then 'Hitman'
when name like 'Indiana Jones%' then 'Indiana Jones'
when name like 'Infinity Blade%' then 'Infinity Blade'
when name like 'James Bond 007%' then 'James Bond 007'
when name like 'JoJos Bizarre Adventure%' then 'JoJos Bizarre Adventure'
when name like 'Jurassic%' then 'Jurassic World'
when name like 'Kings Quest%' then 'Kings Quest'
when name like 'Kingdom Hearts%' then 'Kingdom Hearts'
when name like 'Hitman%' then 'Hitman'
when name like 'Kirby%' then 'Kirby'
when name like 'Lands of Lore%' then 'Lands of Lore'
when name like 'Hitman%' then 'Hitman'
when name like 'Lego%' then 'Lego'
when name like 'Leisure Suit%' then 'Leisure Suit'
when name like 'Luigis Mansion%' then 'Luigis Mansion'
when name like 'Mafia%' then 'Mafia'
when name like 'Mario & Luigi%' then 'Mario & Luigi'
when name like 'Mario Party%' then 'Mario Party'
when name like 'Marvel%' then 'Marvel'
when name like 'Mass Effect%' then 'Mass Effect'
when name like 'Mech Commander%' then 'Mech Commander'
when name like 'MechWarrior%' then 'MechWarrior'
when name like 'Medal of Honor%' then 'Medal of Honor'
when name like 'Mega Man%' then 'Mega Man'
when name like 'Metal Gear%' then 'Metal Gear'
when name like 'Metal Slug%' then 'Metal Slug'
when name like 'Middle-Earth%' then 'Middle-Earth'
when name like 'Might and Magic%' then 'Might and Magic'
when name like 'Mobile Suit Gundam%' then 'Mobile Suit Gundam'
when name like 'Modern Combat%' then 'Modern Combat'
when name like 'Monster Hunter%' then 'Monster Hunter'
when name like 'Monster Rancher%' then 'Monster Rancher'
when name like 'Mortal Kombat%' then 'Mortal Kombat'
when name like 'MotorStorm%' then 'MotorStorm'
when name like 'Mount & Blade%' then 'Mount & Blade'
when name like 'Might and Magic%' then 'Might and Magic'
when name like 'My Friend Pedro%' then 'My Friend Pedro'
when name like 'Myst%' then 'Myst'
when name like 'Mystery Case Files%' then 'Mystery Case Files'
when name like 'Nancy Drew%' then 'Nancy Drew'
when name like 'Naruto%' then 'Naruto'
when name like 'Need for Speed%' then 'Need for Speed'
when name like 'Might and Magic%' then 'Might and Magic'
when name like 'Oddworld%' then 'Oddworld'
when name like 'One Piece%' then 'One Piece'
when name like 'Onimusha%' then 'Onimusha'
when name like 'Pac-Man%' then 'Pac-Man'
when name like 'Persona%' then 'Persona'
when name like 'PokÃ©mon%' then 'Pokemon'
when name like 'Power Rangers%' then 'Power Rangers'
when name like 'Prince of Persia%' then 'Prince of Persia'
when name like 'Professor Layton%' then 'Professor Layton'
when name like 'Putt-Putt%' then 'Putt-Putt'
when name like 'Quest for Glory%' then 'Quest for Glory'
when name like 'Putt-Putt%' then 'Putt-Putt'
when name like 'Rainbow Six%' then 'Rainbow Six'
when name like 'Putt-Putt%' then 'Putt-Putt'
when name like 'Ratchet & Clank%' then 'Ratchet & Clank'
when name like 'Red Dead Redemption%' then 'Red Dead Redemption'
when name like 'Resident Evil%' then 'Resident Evil'
when name like 'Road Rash%' then 'Road Rash'
when name like 'RollerCoaster%' then 'RollerCoaster'
when name like 'Rusty Lake%' then 'Rusty Lake'
when name like 'Saints Row%' then 'Saints Row'
when name like 'Sam & Max%' then 'Sam & Max'
when name like 'Samurai Shodown%' then 'Samurai Shodown'
when name like 'Samurai Warriors%' then 'Samurai Warriors'
when name like 'Scooby-Doo%' then 'Scooby-Doo'
when name like 'Serious Sam%' then 'Serious Sam'
when name like 'Samurai Warriors%' then 'Samurai Warriors'
when name like 'Shadow Hearts%' then 'Shadow Hearts'
when name like 'Sherlock Holmes%' then 'Sherlock Holmes'
when name like 'Sleeping Dogs%' then 'Sleeping Dogs'
when name like 'South Park%' then 'South Park'
when name like 'Splatoon%' then 'Splatoon'
when name like 'SpongeBob SquarePants%' then 'SpongeBob SquarePants'
when name like 'Star Ocean%' then 'Star Ocean'
when name like 'Star Trek%' then 'Star Trek'
when name like 'Star Wars%' then 'Star Wars'
when name like 'Street Fighter%' then 'Street Fighter'
when name like 'Super Mario%' then 'Super Mario'
when name like 'Tales of Monkey Island%' then 'Tales of Monkey Island'
when name like 'Teenage Mutant Ninja Turtles%' then 'Teenage Mutant Ninja Turtles'
when name like 'The King of Fighters%' then 'The King of Fighters'
when name like 'The Legend of Heroes%' then 'The Legend of Heroes'
when name like 'The Legend of Zelda%' then 'The Legend of Zelda'
when name like 'The Room%' then 'The Room'
when name like 'The Simpsons%' then 'The Simpsons'
when name like 'The Walking Dead%' then 'The Walking Dead'
when name like 'Ultima%' then 'Ultima'
when name like 'Twisted Metal%' then 'Twisted Metal'
when name like 'Uncharted%' then 'Uncharted'
when name like 'Vader Immortal%' then 'Vader Immortal'
when name like 'Virtua Fighter%' then 'Virtua Fighter'
when name like 'Twisted Metal%' then 'Twisted Metal'
when name like 'WWE%' or name like 'WWF%' then 'WWE'
when name like 'Warhammer%' then 'Warhammer'
when name like 'Wing Commander%' then 'Wing Commander'
when name like 'Wolfenstein%' then 'Wolfenstein'
when name like 'World of Warcraft%' then 'World of Warcraft'
when name like 'X-Men%' then 'X-Men'
when name like 'Xenoblade Chronicles%' then 'Xenoblade Chronicles'
when name like 'Yakuza%' then 'Yakuza'
when name like 'Yu-Gi-Oh%' then 'Yu-Gi-Oh'
when name like 'Zombie Society%' then 'Zombie Society'
when name like 'Zone of the Enders%' then 'Zone of the Enders'
when name like 'inFamous%' then 'inFamous'


else name end as main_name
from 
(
select * from videogame
where
rating is not null 
or votes is not null
)

where rating > (select avg(rating) from videogame where rating is not null or votes is not null)
and votes >  (select avg(votes) from videogame where rating is not null or votes is not null)
)

select
version.main_name,
version.count_version,
tenure_table.launch_year,
tenure_table.latest_year,
tenure_table.tenure,
tenure_table.last_ten_yrs_launched,
total_votes_table.total_votes,
rating.avg_rating,
rating.min_rating,
rating.max_rating,
rating_avg.rating_counts_greater_than_overall_avg,
count_of_versions_greater_than_avg_rating.total_games_greater_than_avg_rating,
cerifications.distinct_certifications,
generes.distinct_generes,
traffic.traffic_contribution,
row_number () over (order by total_votes_table.total_votes desc,rating.avg_rating desc,rating.min_rating desc,rating.max_rating desc,cerifications.distinct_certifications desc,generes.distinct_generes desc,version.count_version desc,rating_avg.rating_counts_greater_than_overall_avg desc) as row_number,
dense_rank () over (order by total_votes_table.total_votes desc,rating.avg_rating desc,rating.min_rating desc,rating.max_rating desc,cerifications.distinct_certifications desc,generes.distinct_generes desc, version.count_version desc,rating_avg.rating_counts_greater_than_overall_avg desc) as rank_number
from (
select
main_name,
count(name) as count_version
from master_data
group by 1) version

join (
select
main_name,
launch_year,
latest_year,
case when tenure = 0 then 1 else tenure end as tenure,
case when launch_year >= 2012 and latest_year <= 2022 then 'Yes' else 'No' end as last_ten_yrs_launched
from
(
select
main_name,
min(year) as launch_year,
max(year) as latest_year,
max(year)-min(year) as tenure
from master_data
group by 1
)

) tenure_table on version.main_name=tenure_table.main_name

join (

select
main_name,
sum(votes) as total_votes
from master_data
group by 1

) total_votes_table on version.main_name=total_votes_table.main_name


join (

select
main_name,
round(avg(rating),2) as avg_rating,
min(rating) as min_rating,
max(rating) as max_rating
from master_data
group by 1

) rating on version.main_name=rating.main_name

join (

select
main_name,
count(rating) as rating_counts_greater_than_overall_avg
from (
select
main_name,
rating,
round((select avg(rating) from master_data),2) as avg_rating
from master_data
where rating > avg_rating
group by 1,2
)
group by 1


) rating_avg on version.main_name=rating_avg.main_name

join (

select
main_name,
sum(greater_than_avg_rating) as total_games_greater_than_avg_rating
from

(
select
main_name,
name,
rating,
round((select avg(rating) from master_data),2) as avg_rating,
case when rating > round((select avg(rating) from master_data),2) then 1 else 0 end as greater_than_avg_rating
from master_data 
group by 1,2
)
group by 1

) count_of_versions_greater_than_avg_rating on version.main_name=count_of_versions_greater_than_avg_rating.main_name

join (

select
main_name,
count(distinct certificate) as distinct_certifications
from
(
select
distinct
main_name,
name,
certificate
from master_data
group by 1,2
)
group by 1

) cerifications on version.main_name=cerifications.main_name

join (

select
main_name,
(Action + adventure + Comedy + Crime + Family + Fantasy + Mystery + SciFi + Thriller) as distinct_generes

from (
select
main_name,
max(action) as action,
max(adventure) as adventure,
max(comedy) as comedy,
max(crime) as crime,
max(Family) as family,
max(Fantasy) as fantasy,
max(Mystery) as mystery,
max([Sci-Fi]) as scifi,
max(Thriller) as thriller
from
(
select
main_name,
name,
Action,
Adventure,
Comedy,
Crime,
Family,
Fantasy,
Mystery,
[Sci-Fi],
Thriller
from master_data
group by 2
)
group by 1
)


)  generes on version.main_name=generes.main_name

join (

select
main_name,
sum(votes)/(select sum(votes) from master_data) as traffic_contribution
from master_data
group by 1


) traffic on version.main_name=traffic.main_name

order by rank_number asc

''';

    
df_sql = pd.read_sql_query(sql,con=engine)
df_sql.head()

,main_name,count_version,launch_year,latest_year,tenure,last_ten_yrs_launched,total_votes,avg_rating,min_rating,max_rating,rating_counts_greater_than_overall_avg,total_games_greater_than_avg_rating,distinct_certifications,distinct_generes,traffic_contribution,row_number,rank_number
0,Star Wars,55,1982.0,2022.0,40.0,No,11253.0,7.88,7.1,9.5,11,21,5,4,0.013623,1,1
1,Kirby,21,1992.0,2022.0,30.0,No,8597.0,7.91,7.1,9.0,7,11,3,6,0.010408,2,2
2,WWE,20,1993.0,2022.0,29.0,No,8268.0,7.64,7.1,8.5,4,5,3,2,0.010010,3,3
3,Lego,26,1997.0,2018.0,21.0,No,7009.0,7.80,7.1,8.7,6,9,2,6,0.008485,4,4
4,Dragon Ball,27,1992.0,2020.0,28.0,No,6893.0,7.70,7.1,8.7,6,9,3,7,0.008345,5,5

# Phase 2:- We will explore sentiment analysis and add this metric to the query

### Introduction: how to sentimental analysis
### its a practice where we run data over a series of predefined rules, and tell if the text is positive or negative.

for example:- i like pizza very much and i have it daily :- this is a postivie sentence.

for example:- i dont like pizza very much and i dont have it :- this is a negative sentence.

## Next steps forward for phase 2

step 1 :- take the orignal raw data frame

step2 :- filter the plot and the name

step 3:- explore options for cleaning the data, or preprocessing data

step 4:- run the data over a ML script and derive a DF that has names vs text vs senitimental analysis metrics

step 5:- we should figure out a way to add this metric in our original phase 1 project.

pip install textblob

In [35]:
## to filter few colums in the df

df_sentiment=df[['name','plot']].copy()
df_sentiment.head()

,name,plot
0,Spider-Man,"When a new villain threatens New York City, Pe..."
1,Red Dead Redemption II,Amidst the decline of the Wild West at the tur...
2,Grand Theft Auto V,Three very different criminals team up for a s...
3,God of War,"After wiping out the gods of Mount Olympus, Kr..."
4,Uncharted 4: A Thief's End,Thrown back into the dangerous underworld he'd...

In [36]:
## Reference for textblob:- https://www.analyticsvidhya.com/blog/2021/06/rule-based-sentiment-analysis-in-python/

## set up the sentimental analyis package

from textblob import TextBlob
x1='Arvinth is a bad kid'
x2='Arvinth is a good kid'
x3='Arvinth is a very good kid'
x4='Arvinth is a very bad kid'

print(TextBlob(x1).sentiment.polarity)
print(TextBlob(x2).sentiment.polarity)
print(TextBlob(x3).sentiment.polarity)
print(TextBlob(x4).sentiment.polarity)

-0.6999999999999998
0.7
0.9099999999999999
-0.9099999999999998

In [37]:
## the metrics that we see above is called the polarity, it is just a scale of -1 and 1 that helps us understand if the intent is positive or negative

df_sentiment['polarity_score']=''
df_sentiment.head()

,name,plot,polarity_score
0,Spider-Man,"When a new villain threatens New York City, Pe...",
1,Red Dead Redemption II,Amidst the decline of the Wild West at the tur...,
2,Grand Theft Auto V,Three very different criminals team up for a s...,
3,God of War,"After wiping out the gods of Mount Olympus, Kr...",
4,Uncharted 4: A Thief's End,Thrown back into the dangerous underworld he'd...,

In [34]:

#df['plot'][x],TextBlob(df['plot'][x]).sentiment.polarity

#df_sentiment['polarity_score'].iloc[:]=TextBlob(str(df_sentiment['plot'].iloc[:])).sentiment.polarity


for i in range(0, len(df_sentiment)):
    df_sentiment['polarity_score'].values[i]=TextBlob(df_sentiment['plot'].values[i]).sentiment.polarity
    
df_sentiment.head()

,name,plot,polarity_score
0,Spider-Man,"When a new villain threatens New York City, Pe...",0.257576
1,Red Dead Redemption II,Amidst the decline of the Wild West at the tur...,0.05
2,Grand Theft Auto V,Three very different criminals team up for a s...,0.0625
3,God of War,"After wiping out the gods of Mount Olympus, Kr...",-0.75
4,Uncharted 4: A Thief's End,Thrown back into the dangerous underworld he'd...,-0.1875

In [38]:
df_sentiment_final=df_sentiment[['name','polarity_score']]
df_sentiment_final.head()

                         name polarity_score
0                  Spider-Man
1      Red Dead Redemption II
2          Grand Theft Auto V
3                  God of War
4  Uncharted 4: A Thief's End

*NOTE:-* we need to join this dataframe with the sql base and get a query of it

* To solve what is the plan?

* Let's say we are starting the project from 0

* Let's create 2 tables, table 1 is the original raw data and table 2 is sentimental

In [39]:
# import sqlalchemy and create a sqlite engine
from sqlalchemy import create_engine
engine = create_engine('sqlite://', echo=False)

# export the dataframe as a table 'playstore' to the sqlite engine
df_sentiment_final.to_sql("sentiment", con =engine) ## salary dataset is the table name
df.to_sql("videogame", con =engine)

In [41]:
## Master query for Phase 2 in the project!!!

## this is the phase 2 master query which has the sentimental analysis metrics also

sql='''

with master_data as (

select *,
case 
when name like 'Goodbye, Galaxy!%' then 'Goodbye, Galaxy!'
when name like '.hack//%' then '.hack//G.U.'
when name like '13 Sentinels%' then '13 Sentinels'
when name like '3D Pinball for Windows%' then '3D Pinball for Windows'
when name like '80 Days:%' then '80 Days'
when name like 'AI: The Somnium Files%' then 'AI: The Somnium Files'
when name like 'Accounting%' then 'Accounting'
when name like 'Ace Attorney%' then 'Ace Attorney'
when name like 'Ace Combat%' then 'Ace Combat'
when name like 'ActRaiser%' then 'ActRaiser'
when name like 'Advance Wars%' then 'Advance Wars'
when name like 'Adventure%' then 'Adventure'
when name like 'Agatha Christie%' then 'Agatha Christie'
when name like 'Age of Empires%' then 'Age of Empires'
when name like 'Age of Wonders%' then 'Age of Wonders'
when name like 'Adventure%' then 'Adventure'
when name like 'Aladdin%' then 'Aladdin'
when name like 'Alan Wake%' then 'Alan Wake'
when name like 'Alien%' then 'Alien'
when name like 'Aliens%' then 'Aliens'
when name like 'Alone in the Dark%' then 'Alone in the Dark'
when name like 'Alpha%' then 'Alpha'
when name like 'Alter%' then 'Alter'
when name like 'Alto%' then 'Alto'
when name like 'Angry Birds%' then 'Angry Birds'
when name like 'Animal%' then 'Animal'
when name like 'Animaniacs%' then 'Animaniacs'
when name like 'Ape Escape%' then 'Ape Escape'
when name like 'Arc the Lad%' then 'Arc the Lad'
when name like 'Ariel%' then 'Ariel'
when name like 'ArmA%' then 'ArmA'
when name like 'Army Men%' then 'Army Men'
when name like 'Asheron%' then 'Asheron Call'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Assassin%' and name like '%Creed%' then 'Assassin Creed'
when name like 'Atelier Iris%' then 'Atelier Iris'
when name like 'Atlantis%'  then 'Atlantis'
when name like 'Attack on Titan%' then 'Attack on Titan'
when name like 'Avatar%' then 'Avatar'
when name like 'Back to the Future%' then 'Back to the Future'
when name like 'Badland%' then 'Badland'
when name like 'Bakugan%' then 'Bakugan'
when name like 'Baldur%' and name like '%Gate%' then 'Baldur Gate'
when name like 'Barbie%' then 'Barbie'
when name like 'Baten Kaitos%' then 'Baten Kaitos'
when name like 'Battalion Wars%' then 'Battalion Wars'
when name like 'Battlestations%' then 'Battlestations Midway'
when name like '%Battletoads%' then 'Battletoads'
when name like '%Battletoads  Double Dragon%' then 'Battletoads Double Dragon'
when name like '%Battlezone%' then 'Battlezone'
when name like '%Bayonetta & Vanquish 10th Anniversary Bundle%' then 'Bayonetta'
when name like '%Bayonetta 2%' then 'Bayonetta'
when name like '%BeamNG.drive%' then 'BeamNG.drive'
when name like '%Bear in the Big Blue House: Bear Sense of Adventure%' then 'Bear in the Big Blue House: Bear Sense of Adventure'
when name like 'Bear with Me%' then 'Bear with Me'
when name like '%Beat Down: Fists of Vengeance%' then 'Beat Down: Fists of Vengeance'
when name like '%Beautiful Katamari%' then 'Beautiful Katamari'
when name like '%Beavis and Butt-Head%' then 'Beavis and Butt-Head'
when name like 'Beholder%' then 'Beholder'
when name like '%Bendy and the Ink Machine%' then 'Bendy and the Ink Machine'
when name like 'Beyond%' then 'Beyond'
when name like '%BioShock%' then 'BioShock'
when name like '%Black Mirror%' then 'Black Mirror'
when name like 'BlazBlue%' then 'BlazBlue'
when name like 'Blazing Angels%' then 'Blazing Angels'
when name like 'Bloody Roar%' then 'Bloody Roar'
when name like 'Boktai%' then 'Boktai'
when name like 'Bomberman%' then 'Bomberman'
when name like 'Bone%' then 'Bone'
when name like 'Borderlands%' then 'Borderlands'
when name like 'Bloodstained%' then 'Bloodstained'
when name like 'Broken Sword%' then 'Broken Sword'
when name like 'Brothers in Arms%' then 'Brothers in Arms'
when name like 'Buffy the Vampire Slayer%' then 'Buffy the Vampire Slayer'
when name like 'Bugs Bunny%' then 'Bugs Bunny'
when name like 'Bushido Blade%' then 'Bushido Blade'
when name like 'Burnout%' then 'Burnout'
when name like 'CR%' then 'CR'
when name like 'CSI%' then 'CSI'
when name like 'Cadillacs and Dinosaurs%' then 'Cadillacs and Dinosaurs'
when name like 'Call of Duty%' then 'Call of Duty'
when name like 'Call of Juarez%' then 'Call of Juarez'
when name like 'Capcom vs SNK%' then 'Capcom vs SNK'
when name like 'Cat Quest%' then 'Cat Quest'
when name like 'Chaos Rings%' then 'Chaos Rings'
when name like 'Chicken Invaders%' then 'Chicken Invaders'
when name like 'Chip Dale%' then 'Chip Dale'
when name like 'Chivalry%' then 'Chivalry'
when name like 'Close Combat%' then 'Close Combat'
when name like 'Colony Wars%' then 'Colony Wars'
when name like 'Command & Conquer%' then 'Command & Conquer'
when name like 'Castlevania%' then 'Castlevania'
when name like 'Commandos%' then 'Commandos'
when name like 'Castlevania%' then 'Castlevania'
when name like 'Crash Bandicoot%' then 'Crash Bandicoot'
when name like 'Castlevania%' then 'Castlevania'
when name like 'Cube Escape%' then 'Cube Escape'
when name like 'Crysis%' then 'Crysis'
when name like 'Danganronpa%' then 'Danganronpa'
when name like 'Dark Souls%' then 'Dark Souls'
when name like 'Darksiders%' then 'Darksiders'
when name like 'Dead Island%' then 'Dead Island'
when name like 'Dead Space%' then 'Dead Space'
when name like 'Dead or Alive%' then 'Dead or Alive'
when name like 'Deadpool%' then 'Deadpool'
when name like 'Demolition Man%' then 'Demolition Man'
when name like 'Demon Slayer%' then 'Demon Slayer'
when name like 'Descent%' then 'Descent'
when name like 'Deus Ex%' then 'Deus Ex'
when name like 'Devil May Cry%' then 'Devil May Cry'
when name like 'Diablo%' then 'Diablo'
when name like 'Die Hard%' then 'Die Hard'
when name like 'Disciples%' then 'Disciples'
when name like 'Die Hard%' then 'Die Hard'
when name like 'Disgaea%' then 'Disgaea'
when name like 'Dishonored%' then 'Dishonored'
when name like 'Dissidia%' then 'Dissidia'
when name like 'Disney%' then 'Disney'
when name like 'Divinity%' then 'Divinity'
when name like 'Doctor Who%' then 'Doctor Who'
when name like 'Dont Escape%' then 'Dont Escape'
when name like 'Disney%' then 'Disney'
when name like 'Donkey Kong%' then 'Donkey Kong'
when name like 'Doom%' then 'Doom'
when name like 'Double Dragon%' then 'Double Dragon'
when name like 'Dracula%' then 'Dracula'
when name like 'Dragon Age%' then 'Dragon Age'
when name like 'Dragon Ball%' then 'Dragon Ball'
when name like 'Dragon Warrior%' then 'Dragon Warrior'
when name like 'Drakengard%' then 'Drakengard'
when name like 'Duke Nukem%' then 'Duke Nukem'
when name like 'Dungeon%' then 'Dungeon'
when name like 'Dragon Quest%' then 'Dragon Quest'
when name like 'Dynasty Warriors%' then 'Dynasty Warriors'
when name like 'Dragon Quest%' then 'Dragon Quest'
when name like 'Earthworm%' then 'Earthworm'
when name like 'Evil Dead%' then 'Evil Dead'
when name like 'F.E.A.R.%' then 'F.E.A.R.'
when name like 'Fable%' then 'Fable'
when name like 'Dragon Quest%' then 'Dragon Quest'
when name like 'Fallout%' then 'Fallout'
when name like 'Far Cry%' then 'Far Cry'
when name like 'Fatal Frame%' then 'Fatal Frame'
when name like 'Final Fantasy%' then 'Final Fantasy'
when name like 'Fire Emblem%' then 'Fire Emblem'
when name like 'Forza Horizon%' then 'Forza Horizon'
when name like 'Forza Motorsport%' then 'Forza Motorsport'
when name like 'Freddi Fish%' then 'Freddi Fish'
when name like 'Front Mission%' then 'Front Mission'
when name like 'Fullmetal Alchemist%' then 'Fullmetal Alchemist'
when name like 'G.I. Joe%' then 'G.I. Joe'
when name like 'Ghost Recon%' then 'Ghost Recon'
when name like 'Ghost in the Shell%' then 'Ghost in the Shell'
when name like 'God of War%' then 'God of War'
when name like 'Goosebumps%' then 'Goosebumps'
when name like 'Gothic%' then 'Gothic'
when name like 'God of War%' then 'God of War'
when name like 'Grand Theft Auto%' then 'Grand Theft Auto'
when name like 'Gravity Rush%' then 'Gravity Rush'
when name like 'Growlanser%' then 'Growlanser'
when name like 'Guild Wars%' then 'Guild Wars'
when name like 'Guilty Gear%' then 'Guilty Gear'
when name like 'Halo%' then 'Halo'
when name like 'Hatsune Miku%' then 'Hatsune Miku'
when name like 'Heroes of Might and Magic%' then 'Heroes of Might and Magic'
when name like 'Hyperdimension Neptunia%' then 'Hitman'
when name like 'Indiana Jones%' then 'Indiana Jones'
when name like 'Infinity Blade%' then 'Infinity Blade'
when name like 'James Bond 007%' then 'James Bond 007'
when name like 'JoJos Bizarre Adventure%' then 'JoJos Bizarre Adventure'
when name like 'Jurassic%' then 'Jurassic World'
when name like 'Kings Quest%' then 'Kings Quest'
when name like 'Kingdom Hearts%' then 'Kingdom Hearts'
when name like 'Hitman%' then 'Hitman'
when name like 'Kirby%' then 'Kirby'
when name like 'Lands of Lore%' then 'Lands of Lore'
when name like 'Hitman%' then 'Hitman'
when name like 'Lego%' then 'Lego'
when name like 'Leisure Suit%' then 'Leisure Suit'
when name like 'Luigis Mansion%' then 'Luigis Mansion'
when name like 'Mafia%' then 'Mafia'
when name like 'Mario & Luigi%' then 'Mario & Luigi'
when name like 'Mario Party%' then 'Mario Party'
when name like 'Marvel%' then 'Marvel'
when name like 'Mass Effect%' then 'Mass Effect'
when name like 'Mech Commander%' then 'Mech Commander'
when name like 'MechWarrior%' then 'MechWarrior'
when name like 'Medal of Honor%' then 'Medal of Honor'
when name like 'Mega Man%' then 'Mega Man'
when name like 'Metal Gear%' then 'Metal Gear'
when name like 'Metal Slug%' then 'Metal Slug'
when name like 'Middle-Earth%' then 'Middle-Earth'
when name like 'Might and Magic%' then 'Might and Magic'
when name like 'Mobile Suit Gundam%' then 'Mobile Suit Gundam'
when name like 'Modern Combat%' then 'Modern Combat'
when name like 'Monster Hunter%' then 'Monster Hunter'
when name like 'Monster Rancher%' then 'Monster Rancher'
when name like 'Mortal Kombat%' then 'Mortal Kombat'
when name like 'MotorStorm%' then 'MotorStorm'
when name like 'Mount & Blade%' then 'Mount & Blade'
when name like 'Might and Magic%' then 'Might and Magic'
when name like 'My Friend Pedro%' then 'My Friend Pedro'
when name like 'Myst%' then 'Myst'
when name like 'Mystery Case Files%' then 'Mystery Case Files'
when name like 'Nancy Drew%' then 'Nancy Drew'
when name like 'Naruto%' then 'Naruto'
when name like 'Need for Speed%' then 'Need for Speed'
when name like 'Might and Magic%' then 'Might and Magic'
when name like 'Oddworld%' then 'Oddworld'
when name like 'One Piece%' then 'One Piece'
when name like 'Onimusha%' then 'Onimusha'
when name like 'Pac-Man%' then 'Pac-Man'
when name like 'Persona%' then 'Persona'
when name like 'PokÃ©mon%' then 'Pokemon'
when name like 'Power Rangers%' then 'Power Rangers'
when name like 'Prince of Persia%' then 'Prince of Persia'
when name like 'Professor Layton%' then 'Professor Layton'
when name like 'Putt-Putt%' then 'Putt-Putt'
when name like 'Quest for Glory%' then 'Quest for Glory'
when name like 'Putt-Putt%' then 'Putt-Putt'
when name like 'Rainbow Six%' then 'Rainbow Six'
when name like 'Putt-Putt%' then 'Putt-Putt'
when name like 'Ratchet & Clank%' then 'Ratchet & Clank'
when name like 'Red Dead Redemption%' then 'Red Dead Redemption'
when name like 'Resident Evil%' then 'Resident Evil'
when name like 'Road Rash%' then 'Road Rash'
when name like 'RollerCoaster%' then 'RollerCoaster'
when name like 'Rusty Lake%' then 'Rusty Lake'
when name like 'Saints Row%' then 'Saints Row'
when name like 'Sam & Max%' then 'Sam & Max'
when name like 'Samurai Shodown%' then 'Samurai Shodown'
when name like 'Samurai Warriors%' then 'Samurai Warriors'
when name like 'Scooby-Doo%' then 'Scooby-Doo'
when name like 'Serious Sam%' then 'Serious Sam'
when name like 'Samurai Warriors%' then 'Samurai Warriors'
when name like 'Shadow Hearts%' then 'Shadow Hearts'
when name like 'Sherlock Holmes%' then 'Sherlock Holmes'
when name like 'Sleeping Dogs%' then 'Sleeping Dogs'
when name like 'South Park%' then 'South Park'
when name like 'Splatoon%' then 'Splatoon'
when name like 'SpongeBob SquarePants%' then 'SpongeBob SquarePants'
when name like 'Star Ocean%' then 'Star Ocean'
when name like 'Star Trek%' then 'Star Trek'
when name like 'Star Wars%' then 'Star Wars'
when name like 'Street Fighter%' then 'Street Fighter'
when name like 'Super Mario%' then 'Super Mario'
when name like 'Tales of Monkey Island%' then 'Tales of Monkey Island'
when name like 'Teenage Mutant Ninja Turtles%' then 'Teenage Mutant Ninja Turtles'
when name like 'The King of Fighters%' then 'The King of Fighters'
when name like 'The Legend of Heroes%' then 'The Legend of Heroes'
when name like 'The Legend of Zelda%' then 'The Legend of Zelda'
when name like 'The Room%' then 'The Room'
when name like 'The Simpsons%' then 'The Simpsons'
when name like 'The Walking Dead%' then 'The Walking Dead'
when name like 'Ultima%' then 'Ultima'
when name like 'Twisted Metal%' then 'Twisted Metal'
when name like 'Uncharted%' then 'Uncharted'
when name like 'Vader Immortal%' then 'Vader Immortal'
when name like 'Virtua Fighter%' then 'Virtua Fighter'
when name like 'Twisted Metal%' then 'Twisted Metal'
when name like 'WWE%' or name like 'WWF%' then 'WWE'
when name like 'Warhammer%' then 'Warhammer'
when name like 'Wing Commander%' then 'Wing Commander'
when name like 'Wolfenstein%' then 'Wolfenstein'
when name like 'World of Warcraft%' then 'World of Warcraft'
when name like 'X-Men%' then 'X-Men'
when name like 'Xenoblade Chronicles%' then 'Xenoblade Chronicles'
when name like 'Yakuza%' then 'Yakuza'
when name like 'Yu-Gi-Oh%' then 'Yu-Gi-Oh'
when name like 'Zombie Society%' then 'Zombie Society'
when name like 'Zone of the Enders%' then 'Zone of the Enders'
when name like 'inFamous%' then 'inFamous'


else name end as main_name
from 
(
select * from videogame
where
rating is not null 
or votes is not null
)

where rating > (select avg(rating) from videogame where rating is not null or votes is not null)
and votes >  (select avg(votes) from videogame where rating is not null or votes is not null)
),

sentiment_data as
(
Select 
name,
case 
when name like 'Goodbye, Galaxy!%' then 'Goodbye, Galaxy!'
when name like '.hack//%' then '.hack//G.U.'
when name like '13 Sentinels%' then '13 Sentinels'
when name like '3D Pinball for Windows%' then '3D Pinball for Windows'
when name like '80 Days:%' then '80 Days'
when name like 'AI: The Somnium Files%' then 'AI: The Somnium Files'
when name like 'Accounting%' then 'Accounting'
when name like 'Ace Attorney%' then 'Ace Attorney'
when name like 'Ace Combat%' then 'Ace Combat'
when name like 'ActRaiser%' then 'ActRaiser'
when name like 'Advance Wars%' then 'Advance Wars'
when name like 'Adventure%' then 'Adventure'
when name like 'Agatha Christie%' then 'Agatha Christie'
when name like 'Age of Empires%' then 'Age of Empires'
when name like 'Age of Wonders%' then 'Age of Wonders'
when name like 'Adventure%' then 'Adventure'
when name like 'Aladdin%' then 'Aladdin'
when name like 'Alan Wake%' then 'Alan Wake'
when name like 'Alien%' then 'Alien'
when name like 'Aliens%' then 'Aliens'
when name like 'Alone in the Dark%' then 'Alone in the Dark'
when name like 'Alpha%' then 'Alpha'
when name like 'Alter%' then 'Alter'
when name like 'Alto%' then 'Alto'
when name like 'Angry Birds%' then 'Angry Birds'
when name like 'Animal%' then 'Animal'
when name like 'Animaniacs%' then 'Animaniacs'
when name like 'Ape Escape%' then 'Ape Escape'
when name like 'Arc the Lad%' then 'Arc the Lad'
when name like 'Ariel%' then 'Ariel'
when name like 'ArmA%' then 'ArmA'
when name like 'Army Men%' then 'Army Men'
when name like 'Asheron%' then 'Asheron Call'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Assassin%' and name like '%Creed%' then 'Assassin Creed'
when name like 'Atelier Iris%' then 'Atelier Iris'
when name like 'Atlantis%'  then 'Atlantis'
when name like 'Attack on Titan%' then 'Attack on Titan'
when name like 'Avatar%' then 'Avatar'
when name like 'Back to the Future%' then 'Back to the Future'
when name like 'Badland%' then 'Badland'
when name like 'Bakugan%' then 'Bakugan'
when name like 'Baldur%' and name like '%Gate%' then 'Baldur Gate'
when name like 'Barbie%' then 'Barbie'
when name like 'Baten Kaitos%' then 'Baten Kaitos'
when name like 'Battalion Wars%' then 'Battalion Wars'
when name like 'Battlestations%' then 'Battlestations Midway'
when name like '%Battletoads%' then 'Battletoads'
when name like '%Battletoads  Double Dragon%' then 'Battletoads Double Dragon'
when name like '%Battlezone%' then 'Battlezone'
when name like '%Bayonetta & Vanquish 10th Anniversary Bundle%' then 'Bayonetta'
when name like '%Bayonetta 2%' then 'Bayonetta'
when name like '%BeamNG.drive%' then 'BeamNG.drive'
when name like '%Bear in the Big Blue House: Bear Sense of Adventure%' then 'Bear in the Big Blue House: Bear Sense of Adventure'
when name like 'Bear with Me%' then 'Bear with Me'
when name like '%Beat Down: Fists of Vengeance%' then 'Beat Down: Fists of Vengeance'
when name like '%Beautiful Katamari%' then 'Beautiful Katamari'
when name like '%Beavis and Butt-Head%' then 'Beavis and Butt-Head'
when name like 'Beholder%' then 'Beholder'
when name like '%Bendy and the Ink Machine%' then 'Bendy and the Ink Machine'
when name like 'Beyond%' then 'Beyond'
when name like '%BioShock%' then 'BioShock'
when name like '%Black Mirror%' then 'Black Mirror'
when name like 'BlazBlue%' then 'BlazBlue'
when name like 'Blazing Angels%' then 'Blazing Angels'
when name like 'Bloody Roar%' then 'Bloody Roar'
when name like 'Boktai%' then 'Boktai'
when name like 'Bomberman%' then 'Bomberman'
when name like 'Bone%' then 'Bone'
when name like 'Borderlands%' then 'Borderlands'
when name like 'Bloodstained%' then 'Bloodstained'
when name like 'Broken Sword%' then 'Broken Sword'
when name like 'Brothers in Arms%' then 'Brothers in Arms'
when name like 'Buffy the Vampire Slayer%' then 'Buffy the Vampire Slayer'
when name like 'Bugs Bunny%' then 'Bugs Bunny'
when name like 'Bushido Blade%' then 'Bushido Blade'
when name like 'Burnout%' then 'Burnout'
when name like 'CR%' then 'CR'
when name like 'CSI%' then 'CSI'
when name like 'Cadillacs and Dinosaurs%' then 'Cadillacs and Dinosaurs'
when name like 'Call of Duty%' then 'Call of Duty'
when name like 'Call of Juarez%' then 'Call of Juarez'
when name like 'Capcom vs SNK%' then 'Capcom vs SNK'
when name like 'Cat Quest%' then 'Cat Quest'
when name like 'Chaos Rings%' then 'Chaos Rings'
when name like 'Chicken Invaders%' then 'Chicken Invaders'
when name like 'Chip Dale%' then 'Chip Dale'
when name like 'Chivalry%' then 'Chivalry'
when name like 'Close Combat%' then 'Close Combat'
when name like 'Colony Wars%' then 'Colony Wars'
when name like 'Command & Conquer%' then 'Command & Conquer'
when name like 'Castlevania%' then 'Castlevania'
when name like 'Commandos%' then 'Commandos'
when name like 'Castlevania%' then 'Castlevania'
when name like 'Crash Bandicoot%' then 'Crash Bandicoot'
when name like 'Castlevania%' then 'Castlevania'
when name like 'Cube Escape%' then 'Cube Escape'
when name like 'Crysis%' then 'Crysis'
when name like 'Danganronpa%' then 'Danganronpa'
when name like 'Dark Souls%' then 'Dark Souls'
when name like 'Darksiders%' then 'Darksiders'
when name like 'Dead Island%' then 'Dead Island'
when name like 'Dead Space%' then 'Dead Space'
when name like 'Dead or Alive%' then 'Dead or Alive'
when name like 'Deadpool%' then 'Deadpool'
when name like 'Demolition Man%' then 'Demolition Man'
when name like 'Demon Slayer%' then 'Demon Slayer'
when name like 'Descent%' then 'Descent'
when name like 'Deus Ex%' then 'Deus Ex'
when name like 'Devil May Cry%' then 'Devil May Cry'
when name like 'Diablo%' then 'Diablo'
when name like 'Die Hard%' then 'Die Hard'
when name like 'Disciples%' then 'Disciples'
when name like 'Die Hard%' then 'Die Hard'
when name like 'Disgaea%' then 'Disgaea'
when name like 'Dishonored%' then 'Dishonored'
when name like 'Dissidia%' then 'Dissidia'
when name like 'Disney%' then 'Disney'
when name like 'Divinity%' then 'Divinity'
when name like 'Doctor Who%' then 'Doctor Who'
when name like 'Dont Escape%' then 'Dont Escape'
when name like 'Disney%' then 'Disney'
when name like 'Donkey Kong%' then 'Donkey Kong'
when name like 'Doom%' then 'Doom'
when name like 'Double Dragon%' then 'Double Dragon'
when name like 'Dracula%' then 'Dracula'
when name like 'Dragon Age%' then 'Dragon Age'
when name like 'Dragon Ball%' then 'Dragon Ball'
when name like 'Dragon Warrior%' then 'Dragon Warrior'
when name like 'Drakengard%' then 'Drakengard'
when name like 'Duke Nukem%' then 'Duke Nukem'
when name like 'Dungeon%' then 'Dungeon'
when name like 'Dragon Quest%' then 'Dragon Quest'
when name like 'Dynasty Warriors%' then 'Dynasty Warriors'
when name like 'Dragon Quest%' then 'Dragon Quest'
when name like 'Earthworm%' then 'Earthworm'
when name like 'Evil Dead%' then 'Evil Dead'
when name like 'F.E.A.R.%' then 'F.E.A.R.'
when name like 'Fable%' then 'Fable'
when name like 'Dragon Quest%' then 'Dragon Quest'
when name like 'Fallout%' then 'Fallout'
when name like 'Far Cry%' then 'Far Cry'
when name like 'Fatal Frame%' then 'Fatal Frame'
when name like 'Final Fantasy%' then 'Final Fantasy'
when name like 'Fire Emblem%' then 'Fire Emblem'
when name like 'Forza Horizon%' then 'Forza Horizon'
when name like 'Forza Motorsport%' then 'Forza Motorsport'
when name like 'Freddi Fish%' then 'Freddi Fish'
when name like 'Front Mission%' then 'Front Mission'
when name like 'Fullmetal Alchemist%' then 'Fullmetal Alchemist'
when name like 'G.I. Joe%' then 'G.I. Joe'
when name like 'Ghost Recon%' then 'Ghost Recon'
when name like 'Ghost in the Shell%' then 'Ghost in the Shell'
when name like 'God of War%' then 'God of War'
when name like 'Goosebumps%' then 'Goosebumps'
when name like 'Gothic%' then 'Gothic'
when name like 'God of War%' then 'God of War'
when name like 'Grand Theft Auto%' then 'Grand Theft Auto'
when name like 'Gravity Rush%' then 'Gravity Rush'
when name like 'Growlanser%' then 'Growlanser'
when name like 'Guild Wars%' then 'Guild Wars'
when name like 'Guilty Gear%' then 'Guilty Gear'
when name like 'Halo%' then 'Halo'
when name like 'Hatsune Miku%' then 'Hatsune Miku'
when name like 'Heroes of Might and Magic%' then 'Heroes of Might and Magic'
when name like 'Hyperdimension Neptunia%' then 'Hitman'
when name like 'Indiana Jones%' then 'Indiana Jones'
when name like 'Infinity Blade%' then 'Infinity Blade'
when name like 'James Bond 007%' then 'James Bond 007'
when name like 'JoJos Bizarre Adventure%' then 'JoJos Bizarre Adventure'
when name like 'Jurassic%' then 'Jurassic World'
when name like 'Kings Quest%' then 'Kings Quest'
when name like 'Kingdom Hearts%' then 'Kingdom Hearts'
when name like 'Hitman%' then 'Hitman'
when name like 'Kirby%' then 'Kirby'
when name like 'Lands of Lore%' then 'Lands of Lore'
when name like 'Hitman%' then 'Hitman'
when name like 'Lego%' then 'Lego'
when name like 'Leisure Suit%' then 'Leisure Suit'
when name like 'Luigis Mansion%' then 'Luigis Mansion'
when name like 'Mafia%' then 'Mafia'
when name like 'Mario & Luigi%' then 'Mario & Luigi'
when name like 'Mario Party%' then 'Mario Party'
when name like 'Marvel%' then 'Marvel'
when name like 'Mass Effect%' then 'Mass Effect'
when name like 'Mech Commander%' then 'Mech Commander'
when name like 'MechWarrior%' then 'MechWarrior'
when name like 'Medal of Honor%' then 'Medal of Honor'
when name like 'Mega Man%' then 'Mega Man'
when name like 'Metal Gear%' then 'Metal Gear'
when name like 'Metal Slug%' then 'Metal Slug'
when name like 'Middle-Earth%' then 'Middle-Earth'
when name like 'Might and Magic%' then 'Might and Magic'
when name like 'Mobile Suit Gundam%' then 'Mobile Suit Gundam'
when name like 'Modern Combat%' then 'Modern Combat'
when name like 'Monster Hunter%' then 'Monster Hunter'
when name like 'Monster Rancher%' then 'Monster Rancher'
when name like 'Mortal Kombat%' then 'Mortal Kombat'
when name like 'MotorStorm%' then 'MotorStorm'
when name like 'Mount & Blade%' then 'Mount & Blade'
when name like 'Might and Magic%' then 'Might and Magic'
when name like 'My Friend Pedro%' then 'My Friend Pedro'
when name like 'Myst%' then 'Myst'
when name like 'Mystery Case Files%' then 'Mystery Case Files'
when name like 'Nancy Drew%' then 'Nancy Drew'
when name like 'Naruto%' then 'Naruto'
when name like 'Need for Speed%' then 'Need for Speed'
when name like 'Might and Magic%' then 'Might and Magic'
when name like 'Oddworld%' then 'Oddworld'
when name like 'One Piece%' then 'One Piece'
when name like 'Onimusha%' then 'Onimusha'
when name like 'Pac-Man%' then 'Pac-Man'
when name like 'Persona%' then 'Persona'
when name like 'PokÃ©mon%' then 'Pokemon'
when name like 'Power Rangers%' then 'Power Rangers'
when name like 'Prince of Persia%' then 'Prince of Persia'
when name like 'Professor Layton%' then 'Professor Layton'
when name like 'Putt-Putt%' then 'Putt-Putt'
when name like 'Quest for Glory%' then 'Quest for Glory'
when name like 'Putt-Putt%' then 'Putt-Putt'
when name like 'Rainbow Six%' then 'Rainbow Six'
when name like 'Putt-Putt%' then 'Putt-Putt'
when name like 'Ratchet & Clank%' then 'Ratchet & Clank'
when name like 'Red Dead Redemption%' then 'Red Dead Redemption'
when name like 'Resident Evil%' then 'Resident Evil'
when name like 'Road Rash%' then 'Road Rash'
when name like 'RollerCoaster%' then 'RollerCoaster'
when name like 'Rusty Lake%' then 'Rusty Lake'
when name like 'Saints Row%' then 'Saints Row'
when name like 'Sam & Max%' then 'Sam & Max'
when name like 'Samurai Shodown%' then 'Samurai Shodown'
when name like 'Samurai Warriors%' then 'Samurai Warriors'
when name like 'Scooby-Doo%' then 'Scooby-Doo'
when name like 'Serious Sam%' then 'Serious Sam'
when name like 'Samurai Warriors%' then 'Samurai Warriors'
when name like 'Shadow Hearts%' then 'Shadow Hearts'
when name like 'Sherlock Holmes%' then 'Sherlock Holmes'
when name like 'Sleeping Dogs%' then 'Sleeping Dogs'
when name like 'South Park%' then 'South Park'
when name like 'Splatoon%' then 'Splatoon'
when name like 'SpongeBob SquarePants%' then 'SpongeBob SquarePants'
when name like 'Star Ocean%' then 'Star Ocean'
when name like 'Star Trek%' then 'Star Trek'
when name like 'Star Wars%' then 'Star Wars'
when name like 'Street Fighter%' then 'Street Fighter'
when name like 'Super Mario%' then 'Super Mario'
when name like 'Tales of Monkey Island%' then 'Tales of Monkey Island'
when name like 'Teenage Mutant Ninja Turtles%' then 'Teenage Mutant Ninja Turtles'
when name like 'The King of Fighters%' then 'The King of Fighters'
when name like 'The Legend of Heroes%' then 'The Legend of Heroes'
when name like 'The Legend of Zelda%' then 'The Legend of Zelda'
when name like 'The Room%' then 'The Room'
when name like 'The Simpsons%' then 'The Simpsons'
when name like 'The Walking Dead%' then 'The Walking Dead'
when name like 'Ultima%' then 'Ultima'
when name like 'Twisted Metal%' then 'Twisted Metal'
when name like 'Uncharted%' then 'Uncharted'
when name like 'Vader Immortal%' then 'Vader Immortal'
when name like 'Virtua Fighter%' then 'Virtua Fighter'
when name like 'Twisted Metal%' then 'Twisted Metal'
when name like 'WWE%' or name like 'WWF%' then 'WWE'
when name like 'Warhammer%' then 'Warhammer'
when name like 'Wing Commander%' then 'Wing Commander'
when name like 'Wolfenstein%' then 'Wolfenstein'
when name like 'World of Warcraft%' then 'World of Warcraft'
when name like 'X-Men%' then 'X-Men'
when name like 'Xenoblade Chronicles%' then 'Xenoblade Chronicles'
when name like 'Yakuza%' then 'Yakuza'
when name like 'Yu-Gi-Oh%' then 'Yu-Gi-Oh'
when name like 'Zombie Society%' then 'Zombie Society'
when name like 'Zone of the Enders%' then 'Zone of the Enders'
when name like 'inFamous%' then 'inFamous'


else name end as main_name,
polarity_score
from sentiment
)





select
version.main_name,
version.count_version,
tenure_table.launch_year,
tenure_table.latest_year,
tenure_table.tenure,
tenure_table.last_ten_yrs_launched,
total_votes_table.total_votes,
rating.avg_rating,
rating.min_rating,
rating.max_rating,
rating_avg.rating_counts_greater_than_overall_avg,
count_of_versions_greater_than_avg_rating.total_games_greater_than_avg_rating,
cerifications.distinct_certifications,
generes.distinct_generes,
traffic.traffic_contribution,
sentiment_data_final.avg_polarity_score,
row_number () over (order by total_votes_table.total_votes desc,rating.avg_rating desc,rating.min_rating desc,rating.max_rating desc,cerifications.distinct_certifications desc,generes.distinct_generes desc,version.count_version desc,rating_avg.rating_counts_greater_than_overall_avg desc) as row_number,
dense_rank () over (order by total_votes_table.total_votes desc,rating.avg_rating desc,rating.min_rating desc,rating.max_rating desc,cerifications.distinct_certifications desc,generes.distinct_generes desc, version.count_version desc,rating_avg.rating_counts_greater_than_overall_avg desc) as rank_number
from (
select
main_name,
count(name) as count_version
from master_data
group by 1) version

join (
select
main_name,
launch_year,
latest_year,
case when tenure = 0 then 1 else tenure end as tenure,
case when launch_year >= 2012 and latest_year <= 2022 then 'Yes' else 'No' end as last_ten_yrs_launched
from
(
select
main_name,
min(year) as launch_year,
max(year) as latest_year,
max(year)-min(year) as tenure
from master_data
group by 1
)

) tenure_table on version.main_name=tenure_table.main_name

join (

select
main_name,
sum(votes) as total_votes
from master_data
group by 1

) total_votes_table on version.main_name=total_votes_table.main_name


join (

select
main_name,
round(avg(rating),2) as avg_rating,
min(rating) as min_rating,
max(rating) as max_rating
from master_data
group by 1

) rating on version.main_name=rating.main_name

join (

select
main_name,
count(rating) as rating_counts_greater_than_overall_avg
from (
select
main_name,
rating,
round((select avg(rating) from master_data),2) as avg_rating
from master_data
where rating > avg_rating
group by 1,2
)
group by 1


) rating_avg on version.main_name=rating_avg.main_name

join (

select
main_name,
sum(greater_than_avg_rating) as total_games_greater_than_avg_rating
from

(
select
main_name,
name,
rating,
round((select avg(rating) from master_data),2) as avg_rating,
case when rating > round((select avg(rating) from master_data),2) then 1 else 0 end as greater_than_avg_rating
from master_data 
group by 1,2
)
group by 1

) count_of_versions_greater_than_avg_rating on version.main_name=count_of_versions_greater_than_avg_rating.main_name

join (

select
main_name,
count(distinct certificate) as distinct_certifications
from
(
select
distinct
main_name,
name,
certificate
from master_data
group by 1,2
)
group by 1

) cerifications on version.main_name=cerifications.main_name

join (

select
main_name,
(Action + adventure + Comedy + Crime + Family + Fantasy + Mystery + SciFi + Thriller) as distinct_generes

from (
select
main_name,
max(action) as action,
max(adventure) as adventure,
max(comedy) as comedy,
max(crime) as crime,
max(Family) as family,
max(Fantasy) as fantasy,
max(Mystery) as mystery,
max([Sci-Fi]) as scifi,
max(Thriller) as thriller
from
(
select
main_name,
name,
Action,
Adventure,
Comedy,
Crime,
Family,
Fantasy,
Mystery,
[Sci-Fi],
Thriller
from master_data
group by 2
)
group by 1
)


)  generes on version.main_name=generes.main_name

join (

select
main_name,
sum(votes)/(select sum(votes) from master_data) as traffic_contribution
from master_data
group by 1


) traffic on version.main_name=traffic.main_name

join (
select
main_name,
avg(polarity_score) as avg_polarity_score
from sentiment_data
group by 1
) sentiment_data_final on version.main_name = sentiment_data_final.main_name

order by rank_number asc

''';

    
df_sql = pd.read_sql_query(sql,con=engine)
df_sql.head()

,main_name,count_version,launch_year,latest_year,tenure,last_ten_yrs_launched,total_votes,avg_rating,min_rating,max_rating,rating_counts_greater_than_overall_avg,total_games_greater_than_avg_rating,distinct_certifications,distinct_generes,traffic_contribution,avg_polarity_score,row_number,rank_number
0,Star Wars,55,1982.0,2022.0,40.0,No,11253.0,7.88,7.1,9.5,11,21,5,4,0.013623,0.0,1,1
1,Kirby,21,1992.0,2022.0,30.0,No,8597.0,7.91,7.1,9.0,7,11,3,6,0.010408,0.0,2,2
2,WWE,20,1993.0,2022.0,29.0,No,8268.0,7.64,7.1,8.5,4,5,3,2,0.010010,0.0,3,3
3,Lego,26,1997.0,2018.0,21.0,No,7009.0,7.80,7.1,8.7,6,9,2,6,0.008485,0.0,4,4
4,Dragon Ball,27,1992.0,2020.0,28.0,No,6893.0,7.70,7.1,8.7,6,9,3,7,0.008345,0.0,5,5

## this is our playground query for sentimental metrics preparation

In [42]:
sql='''

with sentiment_data as
(
Select 
name,
case 
when name like 'Goodbye, Galaxy!%' then 'Goodbye, Galaxy!'
when name like '.hack//%' then '.hack//G.U.'
when name like '13 Sentinels%' then '13 Sentinels'
when name like '3D Pinball for Windows%' then '3D Pinball for Windows'
when name like '80 Days:%' then '80 Days'
when name like 'AI: The Somnium Files%' then 'AI: The Somnium Files'
when name like 'Accounting%' then 'Accounting'
when name like 'Ace Attorney%' then 'Ace Attorney'
when name like 'Ace Combat%' then 'Ace Combat'
when name like 'ActRaiser%' then 'ActRaiser'
when name like 'Advance Wars%' then 'Advance Wars'
when name like 'Adventure%' then 'Adventure'
when name like 'Agatha Christie%' then 'Agatha Christie'
when name like 'Age of Empires%' then 'Age of Empires'
when name like 'Age of Wonders%' then 'Age of Wonders'
when name like 'Adventure%' then 'Adventure'
when name like 'Aladdin%' then 'Aladdin'
when name like 'Alan Wake%' then 'Alan Wake'
when name like 'Alien%' then 'Alien'
when name like 'Aliens%' then 'Aliens'
when name like 'Alone in the Dark%' then 'Alone in the Dark'
when name like 'Alpha%' then 'Alpha'
when name like 'Alter%' then 'Alter'
when name like 'Alto%' then 'Alto'
when name like 'Angry Birds%' then 'Angry Birds'
when name like 'Animal%' then 'Animal'
when name like 'Animaniacs%' then 'Animaniacs'
when name like 'Ape Escape%' then 'Ape Escape'
when name like 'Arc the Lad%' then 'Arc the Lad'
when name like 'Ariel%' then 'Ariel'
when name like 'ArmA%' then 'ArmA'
when name like 'Army Men%' then 'Army Men'
when name like 'Asheron%' then 'Asheron Call'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Alien%' then 'Alien'
when name like 'Assassin%' and name like '%Creed%' then 'Assassin Creed'
when name like 'Atelier Iris%' then 'Atelier Iris'
when name like 'Atlantis%'  then 'Atlantis'
when name like 'Attack on Titan%' then 'Attack on Titan'
when name like 'Avatar%' then 'Avatar'
when name like 'Back to the Future%' then 'Back to the Future'
when name like 'Badland%' then 'Badland'
when name like 'Bakugan%' then 'Bakugan'
when name like 'Baldur%' and name like '%Gate%' then 'Baldur Gate'
when name like 'Barbie%' then 'Barbie'
when name like 'Baten Kaitos%' then 'Baten Kaitos'
when name like 'Battalion Wars%' then 'Battalion Wars'
when name like 'Battlestations%' then 'Battlestations Midway'
when name like '%Battletoads%' then 'Battletoads'
when name like '%Battletoads  Double Dragon%' then 'Battletoads Double Dragon'
when name like '%Battlezone%' then 'Battlezone'
when name like '%Bayonetta & Vanquish 10th Anniversary Bundle%' then 'Bayonetta'
when name like '%Bayonetta 2%' then 'Bayonetta'
when name like '%BeamNG.drive%' then 'BeamNG.drive'
when name like '%Bear in the Big Blue House: Bear Sense of Adventure%' then 'Bear in the Big Blue House: Bear Sense of Adventure'
when name like 'Bear with Me%' then 'Bear with Me'
when name like '%Beat Down: Fists of Vengeance%' then 'Beat Down: Fists of Vengeance'
when name like '%Beautiful Katamari%' then 'Beautiful Katamari'
when name like '%Beavis and Butt-Head%' then 'Beavis and Butt-Head'
when name like 'Beholder%' then 'Beholder'
when name like '%Bendy and the Ink Machine%' then 'Bendy and the Ink Machine'
when name like 'Beyond%' then 'Beyond'
when name like '%BioShock%' then 'BioShock'
when name like '%Black Mirror%' then 'Black Mirror'
when name like 'BlazBlue%' then 'BlazBlue'
when name like 'Blazing Angels%' then 'Blazing Angels'
when name like 'Bloody Roar%' then 'Bloody Roar'
when name like 'Boktai%' then 'Boktai'
when name like 'Bomberman%' then 'Bomberman'
when name like 'Bone%' then 'Bone'
when name like 'Borderlands%' then 'Borderlands'
when name like 'Bloodstained%' then 'Bloodstained'
when name like 'Broken Sword%' then 'Broken Sword'
when name like 'Brothers in Arms%' then 'Brothers in Arms'
when name like 'Buffy the Vampire Slayer%' then 'Buffy the Vampire Slayer'
when name like 'Bugs Bunny%' then 'Bugs Bunny'
when name like 'Bushido Blade%' then 'Bushido Blade'
when name like 'Burnout%' then 'Burnout'
when name like 'CR%' then 'CR'
when name like 'CSI%' then 'CSI'
when name like 'Cadillacs and Dinosaurs%' then 'Cadillacs and Dinosaurs'
when name like 'Call of Duty%' then 'Call of Duty'
when name like 'Call of Juarez%' then 'Call of Juarez'
when name like 'Capcom vs SNK%' then 'Capcom vs SNK'
when name like 'Cat Quest%' then 'Cat Quest'
when name like 'Chaos Rings%' then 'Chaos Rings'
when name like 'Chicken Invaders%' then 'Chicken Invaders'
when name like 'Chip Dale%' then 'Chip Dale'
when name like 'Chivalry%' then 'Chivalry'
when name like 'Close Combat%' then 'Close Combat'
when name like 'Colony Wars%' then 'Colony Wars'
when name like 'Command & Conquer%' then 'Command & Conquer'
when name like 'Castlevania%' then 'Castlevania'
when name like 'Commandos%' then 'Commandos'
when name like 'Castlevania%' then 'Castlevania'
when name like 'Crash Bandicoot%' then 'Crash Bandicoot'
when name like 'Castlevania%' then 'Castlevania'
when name like 'Cube Escape%' then 'Cube Escape'
when name like 'Crysis%' then 'Crysis'
when name like 'Danganronpa%' then 'Danganronpa'
when name like 'Dark Souls%' then 'Dark Souls'
when name like 'Darksiders%' then 'Darksiders'
when name like 'Dead Island%' then 'Dead Island'
when name like 'Dead Space%' then 'Dead Space'
when name like 'Dead or Alive%' then 'Dead or Alive'
when name like 'Deadpool%' then 'Deadpool'
when name like 'Demolition Man%' then 'Demolition Man'
when name like 'Demon Slayer%' then 'Demon Slayer'
when name like 'Descent%' then 'Descent'
when name like 'Deus Ex%' then 'Deus Ex'
when name like 'Devil May Cry%' then 'Devil May Cry'
when name like 'Diablo%' then 'Diablo'
when name like 'Die Hard%' then 'Die Hard'
when name like 'Disciples%' then 'Disciples'
when name like 'Die Hard%' then 'Die Hard'
when name like 'Disgaea%' then 'Disgaea'
when name like 'Dishonored%' then 'Dishonored'
when name like 'Dissidia%' then 'Dissidia'
when name like 'Disney%' then 'Disney'
when name like 'Divinity%' then 'Divinity'
when name like 'Doctor Who%' then 'Doctor Who'
when name like 'Dont Escape%' then 'Dont Escape'
when name like 'Disney%' then 'Disney'
when name like 'Donkey Kong%' then 'Donkey Kong'
when name like 'Doom%' then 'Doom'
when name like 'Double Dragon%' then 'Double Dragon'
when name like 'Dracula%' then 'Dracula'
when name like 'Dragon Age%' then 'Dragon Age'
when name like 'Dragon Ball%' then 'Dragon Ball'
when name like 'Dragon Warrior%' then 'Dragon Warrior'
when name like 'Drakengard%' then 'Drakengard'
when name like 'Duke Nukem%' then 'Duke Nukem'
when name like 'Dungeon%' then 'Dungeon'
when name like 'Dragon Quest%' then 'Dragon Quest'
when name like 'Dynasty Warriors%' then 'Dynasty Warriors'
when name like 'Dragon Quest%' then 'Dragon Quest'
when name like 'Earthworm%' then 'Earthworm'
when name like 'Evil Dead%' then 'Evil Dead'
when name like 'F.E.A.R.%' then 'F.E.A.R.'
when name like 'Fable%' then 'Fable'
when name like 'Dragon Quest%' then 'Dragon Quest'
when name like 'Fallout%' then 'Fallout'
when name like 'Far Cry%' then 'Far Cry'
when name like 'Fatal Frame%' then 'Fatal Frame'
when name like 'Final Fantasy%' then 'Final Fantasy'
when name like 'Fire Emblem%' then 'Fire Emblem'
when name like 'Forza Horizon%' then 'Forza Horizon'
when name like 'Forza Motorsport%' then 'Forza Motorsport'
when name like 'Freddi Fish%' then 'Freddi Fish'
when name like 'Front Mission%' then 'Front Mission'
when name like 'Fullmetal Alchemist%' then 'Fullmetal Alchemist'
when name like 'G.I. Joe%' then 'G.I. Joe'
when name like 'Ghost Recon%' then 'Ghost Recon'
when name like 'Ghost in the Shell%' then 'Ghost in the Shell'
when name like 'God of War%' then 'God of War'
when name like 'Goosebumps%' then 'Goosebumps'
when name like 'Gothic%' then 'Gothic'
when name like 'God of War%' then 'God of War'
when name like 'Grand Theft Auto%' then 'Grand Theft Auto'
when name like 'Gravity Rush%' then 'Gravity Rush'
when name like 'Growlanser%' then 'Growlanser'
when name like 'Guild Wars%' then 'Guild Wars'
when name like 'Guilty Gear%' then 'Guilty Gear'
when name like 'Halo%' then 'Halo'
when name like 'Hatsune Miku%' then 'Hatsune Miku'
when name like 'Heroes of Might and Magic%' then 'Heroes of Might and Magic'
when name like 'Hyperdimension Neptunia%' then 'Hitman'
when name like 'Indiana Jones%' then 'Indiana Jones'
when name like 'Infinity Blade%' then 'Infinity Blade'
when name like 'James Bond 007%' then 'James Bond 007'
when name like 'JoJos Bizarre Adventure%' then 'JoJos Bizarre Adventure'
when name like 'Jurassic%' then 'Jurassic World'
when name like 'Kings Quest%' then 'Kings Quest'
when name like 'Kingdom Hearts%' then 'Kingdom Hearts'
when name like 'Hitman%' then 'Hitman'
when name like 'Kirby%' then 'Kirby'
when name like 'Lands of Lore%' then 'Lands of Lore'
when name like 'Hitman%' then 'Hitman'
when name like 'Lego%' then 'Lego'
when name like 'Leisure Suit%' then 'Leisure Suit'
when name like 'Luigis Mansion%' then 'Luigis Mansion'
when name like 'Mafia%' then 'Mafia'
when name like 'Mario & Luigi%' then 'Mario & Luigi'
when name like 'Mario Party%' then 'Mario Party'
when name like 'Marvel%' then 'Marvel'
when name like 'Mass Effect%' then 'Mass Effect'
when name like 'Mech Commander%' then 'Mech Commander'
when name like 'MechWarrior%' then 'MechWarrior'
when name like 'Medal of Honor%' then 'Medal of Honor'
when name like 'Mega Man%' then 'Mega Man'
when name like 'Metal Gear%' then 'Metal Gear'
when name like 'Metal Slug%' then 'Metal Slug'
when name like 'Middle-Earth%' then 'Middle-Earth'
when name like 'Might and Magic%' then 'Might and Magic'
when name like 'Mobile Suit Gundam%' then 'Mobile Suit Gundam'
when name like 'Modern Combat%' then 'Modern Combat'
when name like 'Monster Hunter%' then 'Monster Hunter'
when name like 'Monster Rancher%' then 'Monster Rancher'
when name like 'Mortal Kombat%' then 'Mortal Kombat'
when name like 'MotorStorm%' then 'MotorStorm'
when name like 'Mount & Blade%' then 'Mount & Blade'
when name like 'Might and Magic%' then 'Might and Magic'
when name like 'My Friend Pedro%' then 'My Friend Pedro'
when name like 'Myst%' then 'Myst'
when name like 'Mystery Case Files%' then 'Mystery Case Files'
when name like 'Nancy Drew%' then 'Nancy Drew'
when name like 'Naruto%' then 'Naruto'
when name like 'Need for Speed%' then 'Need for Speed'
when name like 'Might and Magic%' then 'Might and Magic'
when name like 'Oddworld%' then 'Oddworld'
when name like 'One Piece%' then 'One Piece'
when name like 'Onimusha%' then 'Onimusha'
when name like 'Pac-Man%' then 'Pac-Man'
when name like 'Persona%' then 'Persona'
when name like 'PokÃ©mon%' then 'Pokemon'
when name like 'Power Rangers%' then 'Power Rangers'
when name like 'Prince of Persia%' then 'Prince of Persia'
when name like 'Professor Layton%' then 'Professor Layton'
when name like 'Putt-Putt%' then 'Putt-Putt'
when name like 'Quest for Glory%' then 'Quest for Glory'
when name like 'Putt-Putt%' then 'Putt-Putt'
when name like 'Rainbow Six%' then 'Rainbow Six'
when name like 'Putt-Putt%' then 'Putt-Putt'
when name like 'Ratchet & Clank%' then 'Ratchet & Clank'
when name like 'Red Dead Redemption%' then 'Red Dead Redemption'
when name like 'Resident Evil%' then 'Resident Evil'
when name like 'Road Rash%' then 'Road Rash'
when name like 'RollerCoaster%' then 'RollerCoaster'
when name like 'Rusty Lake%' then 'Rusty Lake'
when name like 'Saints Row%' then 'Saints Row'
when name like 'Sam & Max%' then 'Sam & Max'
when name like 'Samurai Shodown%' then 'Samurai Shodown'
when name like 'Samurai Warriors%' then 'Samurai Warriors'
when name like 'Scooby-Doo%' then 'Scooby-Doo'
when name like 'Serious Sam%' then 'Serious Sam'
when name like 'Samurai Warriors%' then 'Samurai Warriors'
when name like 'Shadow Hearts%' then 'Shadow Hearts'
when name like 'Sherlock Holmes%' then 'Sherlock Holmes'
when name like 'Sleeping Dogs%' then 'Sleeping Dogs'
when name like 'South Park%' then 'South Park'
when name like 'Splatoon%' then 'Splatoon'
when name like 'SpongeBob SquarePants%' then 'SpongeBob SquarePants'
when name like 'Star Ocean%' then 'Star Ocean'
when name like 'Star Trek%' then 'Star Trek'
when name like 'Star Wars%' then 'Star Wars'
when name like 'Street Fighter%' then 'Street Fighter'
when name like 'Super Mario%' then 'Super Mario'
when name like 'Tales of Monkey Island%' then 'Tales of Monkey Island'
when name like 'Teenage Mutant Ninja Turtles%' then 'Teenage Mutant Ninja Turtles'
when name like 'The King of Fighters%' then 'The King of Fighters'
when name like 'The Legend of Heroes%' then 'The Legend of Heroes'
when name like 'The Legend of Zelda%' then 'The Legend of Zelda'
when name like 'The Room%' then 'The Room'
when name like 'The Simpsons%' then 'The Simpsons'
when name like 'The Walking Dead%' then 'The Walking Dead'
when name like 'Ultima%' then 'Ultima'
when name like 'Twisted Metal%' then 'Twisted Metal'
when name like 'Uncharted%' then 'Uncharted'
when name like 'Vader Immortal%' then 'Vader Immortal'
when name like 'Virtua Fighter%' then 'Virtua Fighter'
when name like 'Twisted Metal%' then 'Twisted Metal'
when name like 'WWE%' or name like 'WWF%' then 'WWE'
when name like 'Warhammer%' then 'Warhammer'
when name like 'Wing Commander%' then 'Wing Commander'
when name like 'Wolfenstein%' then 'Wolfenstein'
when name like 'World of Warcraft%' then 'World of Warcraft'
when name like 'X-Men%' then 'X-Men'
when name like 'Xenoblade Chronicles%' then 'Xenoblade Chronicles'
when name like 'Yakuza%' then 'Yakuza'
when name like 'Yu-Gi-Oh%' then 'Yu-Gi-Oh'
when name like 'Zombie Society%' then 'Zombie Society'
when name like 'Zone of the Enders%' then 'Zone of the Enders'
when name like 'inFamous%' then 'inFamous'


else name end as main_name,
polarity_score
from sentiment
)


select
main_name,
avg(polarity_score) as final_score
from sentiment_data
group by 1
''';

    
df_sql = pd.read_sql_query(sql,con=engine)
df_sql.head()

                                           main_name  final_score
0                        #IDARB (It Draws a Red Box)          0.0
1                                            #Murder          0.0
2                                     #OneMoment ARG          0.0
3                                   '99 The Last War          0.0
4  'Goodbye, Galaxy!' Episode IV: Secret of the O...          0.0